version: "3.9"

services:
  app:
    build:
      dockerfile: server/Dockerfile
    container_name: go-app
    ports:
      - "8000:8000"
    environment:
      JWT_SECRET_KEY: "secret"
      JWT_ACCESS_DURATION: "60"
      JWT_REFRESH_DURATION: "3600"
      JWT_ISSUER: "learnHUB-OS"
      SMTP_FROM: "<email>"
      SMTP_PASSWORD: "<pwd>"
      SMTP_HOST: "smtp.mail.ru"
      SMTP_PORT: "587"
      LOG_LEVEL: "DEBUG"
    restart: unless-stopped
