version: "3.9"

services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: server
    ports:
      - "8000:8000"
    environment:
      JWT_SECRET_KEY: "secret"
      JWT_ACCESS_DURATION: "60"
      JWT_REFRESH_DURATION: "3600"
      JWT_ISSUER: "learnHUB-OS"
      SMTP_FROM: "<email>"
      SMTP_PASSWORD: "<pwd>"
      SMTP_HOST: "smtp.mail.ru"
      SMTP_PORT: "587"
      LOG_LEVEL: "DEBUG"
    restart: unless-stopped
  database:
    build:
      context: ./database
      dockerfile: Dockerfile
    container_name: database
    environment:
      POSTGRES_DB: learnHUB
      POSTGRES_USER: server
      POSTGRES_PASSWORD: secret
    ports:
      - "8001:5432"