version: "3.9"

services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    depends_on:
      - database
    container_name: server
    ports:
      - "8000:8000"
    environment:
      POSTGRES_DATABASE: learnHUB
      POSTGRES_USER: server
      POSTGRES_PASSWORD: secret
      POSTGRES_HOST: database
      POSTGRES_PORT: 5432
      POSTGRES_SSLMODE: disable

      SERVE_HOST: 0.0.0.0
      SERVE_PORT: 8000
    restart: unless-stopped
    
  database:
    image: postgres:18
    container_name: database
    environment:
      POSTGRES_DB: learnHUB
      POSTGRES_USER: server
      POSTGRES_PASSWORD: secret
    volumes:
      - ./server/migrations/init.sql:/docker-entrypoint-initdb.d/init.sql
  
  pgadmin:
    image: dpage/pgadmin4:9.12.0
    container_name: pgadmin
    depends_on:
      - database
    environment:
      PGADMIN_DEFAULT_EMAIL: yanushkevichvladislav@mail.ru
      PGADMIN_DEFAULT_PASSWORD: HbC#KtI3e%qe
    ports:
      - "8001:80"
      - "8443:443"