// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: account.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const deleteAccountCredential = `-- name: DeleteAccountCredential :exec
DELETE FROM account.credential
WHERE account_id = $1
`

func (q *Queries) DeleteAccountCredential(ctx context.Context, accountID uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteAccountCredential, accountID)
	return err
}

const insertAccountCredential = `-- name: InsertAccountCredential :exec
INSERT INTO account.credential (
    account_id,
    email,
    pwd_hash
)
VALUES (
    $1,
    $2,
    $3
)
`

type InsertAccountCredentialParams struct {
	AccountID uuid.UUID `db:"account_id" json:"account_id"`
	Email     string    `db:"email" json:"email"`
	PwdHash   string    `db:"pwd_hash" json:"pwd_hash"`
}

func (q *Queries) InsertAccountCredential(ctx context.Context, arg InsertAccountCredentialParams) error {
	_, err := q.db.ExecContext(ctx, insertAccountCredential, arg.AccountID, arg.Email, arg.PwdHash)
	return err
}

const insertAccountProfile = `-- name: InsertAccountProfile :exec
INSERT INTO account.profile (
    account_id,
    first_name,
    last_name,
    role,
    created_at
)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5
)
`

type InsertAccountProfileParams struct {
	AccountID uuid.UUID       `db:"account_id" json:"account_id"`
	FirstName string          `db:"first_name" json:"first_name"`
	LastName  string          `db:"last_name" json:"last_name"`
	Role      AccountUserRole `db:"role" json:"role"`
	CreatedAt time.Time       `db:"created_at" json:"created_at"`
}

func (q *Queries) InsertAccountProfile(ctx context.Context, arg InsertAccountProfileParams) error {
	_, err := q.db.ExecContext(ctx, insertAccountProfile,
		arg.AccountID,
		arg.FirstName,
		arg.LastName,
		arg.Role,
		arg.CreatedAt,
	)
	return err
}

const insertAccountStudent = `-- name: InsertAccountStudent :exec
INSERT INTO account.student (
    account_id,
    group_id
)
VALUES (
    $1,
    $2
)
`

type InsertAccountStudentParams struct {
	AccountID uuid.UUID `db:"account_id" json:"account_id"`
	GroupID   uuid.UUID `db:"group_id" json:"group_id"`
}

func (q *Queries) InsertAccountStudent(ctx context.Context, arg InsertAccountStudentParams) error {
	_, err := q.db.ExecContext(ctx, insertAccountStudent, arg.AccountID, arg.GroupID)
	return err
}

const insertAccountTeacher = `-- name: InsertAccountTeacher :exec
INSERT INTO account.teacher (
    account_id,
    group_id
)
VALUES (
    $1,
    $2
)
`

type InsertAccountTeacherParams struct {
	AccountID uuid.UUID `db:"account_id" json:"account_id"`
	GroupID   uuid.UUID `db:"group_id" json:"group_id"`
}

func (q *Queries) InsertAccountTeacher(ctx context.Context, arg InsertAccountTeacherParams) error {
	_, err := q.db.ExecContext(ctx, insertAccountTeacher, arg.AccountID, arg.GroupID)
	return err
}

const updateAccountProfile = `-- name: UpdateAccountProfile :exec
UPDATE account.profile
SET 
    first_name = $1,
    last_name = $2,
    role = $3
WHERE account_id = $4
`

type UpdateAccountProfileParams struct {
	FirstName string          `db:"first_name" json:"first_name"`
	LastName  string          `db:"last_name" json:"last_name"`
	Role      AccountUserRole `db:"role" json:"role"`
	AccountID uuid.UUID       `db:"account_id" json:"account_id"`
}

func (q *Queries) UpdateAccountProfile(ctx context.Context, arg UpdateAccountProfileParams) error {
	_, err := q.db.ExecContext(ctx, updateAccountProfile,
		arg.FirstName,
		arg.LastName,
		arg.Role,
		arg.AccountID,
	)
	return err
}
