// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: domain.sql

package sqlc

import (
	"context"
	"database/sql"
	"encoding/json"
	"time"

	"github.com/google/uuid"
	"github.com/lib/pq"
)

const getDomainAttempt = `-- name: GetDomainAttempt :one
SELECT 
    att.id,
    att.number_attempt,
    att.quiz_id,
    att.user_id,
    att.score,
    att.started_at,
    att.ended_at,
    COALESCE(a.answers, '[]')::JSONB AS answers
FROM quiz.attempt AS att
LEFT JOIN LATERAL (
    SELECT json_agg(
        json_build_object(
            'id', a.id,
            'question_id', a.question_id,
            'score', a.score,
            'is_correct', a.is_correct,
            'type', q.type,
            'single_selected_answer', COALESCE(s.selected_answer, '')::TEXT,
            'multiple_selected_answer', COALESCE(m.selected_answer, '{}')::TEXT[],
            'numeric_selected_answer', COALESCE(n.selected_answer, 0)::FLOAT
        )
    ) AS answers
    FROM quiz.answer AS a
    INNER JOIN quiz.question AS q ON q.id = a.question_id
    LEFT JOIN quiz.answer_single AS s ON s.answer_id = a.id
    LEFT JOIN quiz.answer_multiple AS m ON m.answer_id = a.id
    LEFT JOIN quiz.answer_numeric AS n ON n.answer_id = a.id
    WHERE a.attempt_id = att.id
) as a ON true
WHERE att.id = $1
`

type GetDomainAttemptRow struct {
	ID            uuid.UUID       `db:"id" json:"id"`
	NumberAttempt int16           `db:"number_attempt" json:"number_attempt"`
	QuizID        uuid.UUID       `db:"quiz_id" json:"quiz_id"`
	UserID        uuid.UUID       `db:"user_id" json:"user_id"`
	Score         int             `db:"score" json:"score"`
	StartedAt     time.Time       `db:"started_at" json:"started_at"`
	EndedAt       sql.NullTime    `db:"ended_at" json:"ended_at"`
	Answers       json.RawMessage `db:"answers" json:"answers"`
}

func (q *Queries) GetDomainAttempt(ctx context.Context, id uuid.UUID) (GetDomainAttemptRow, error) {
	row := q.db.QueryRowContext(ctx, getDomainAttempt, id)
	var i GetDomainAttemptRow
	err := row.Scan(
		&i.ID,
		&i.NumberAttempt,
		&i.QuizID,
		&i.UserID,
		&i.Score,
		&i.StartedAt,
		&i.EndedAt,
		&i.Answers,
	)
	return i, err
}

const getDomainAttempts = `-- name: GetDomainAttempts :many
SELECT 
    a.id,
    a.number_attempt,
    a.quiz_id,
    a.user_id,
    a.score,
    a.started_at,
    a.ended_at
FROM quiz.attempt AS a
`

func (q *Queries) GetDomainAttempts(ctx context.Context) ([]QuizAttempt, error) {
	rows, err := q.db.QueryContext(ctx, getDomainAttempts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []QuizAttempt
	for rows.Next() {
		var i QuizAttempt
		if err := rows.Scan(
			&i.ID,
			&i.NumberAttempt,
			&i.QuizID,
			&i.UserID,
			&i.Score,
			&i.StartedAt,
			&i.EndedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDomainGroup = `-- name: GetDomainGroup :one
SELECT
    g.id,
    g.name,
    t.account_id AS curator_id,
    array_agg(s.account_id)::UUID[] AS student_ids
FROM school.group AS g
LEFT JOIN account.teacher AS t
    ON t.group_id = g.id
LEFT JOIN account.student AS s
    ON s.group_id = g.id
WHERE g.id = $1
GROUP BY g.id, g.name, t.account_id
`

type GetDomainGroupRow struct {
	ID         uuid.UUID     `db:"id" json:"id"`
	Name       string        `db:"name" json:"name"`
	CuratorID  uuid.NullUUID `db:"curator_id" json:"curator_id"`
	StudentIds []uuid.UUID   `db:"student_ids" json:"student_ids"`
}

func (q *Queries) GetDomainGroup(ctx context.Context, id uuid.UUID) (GetDomainGroupRow, error) {
	row := q.db.QueryRowContext(ctx, getDomainGroup, id)
	var i GetDomainGroupRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CuratorID,
		pq.Array(&i.StudentIds),
	)
	return i, err
}

const getDomainQuiz = `-- name: GetDomainQuiz :one
SELECT 
    i.quiz_id,
    i.title,
    i.summary,
    i.owner_id,
    i.subject_id,
    i.max_attempts,
    i.deadline,
    i.total_score,
    i.created_at,
    COALESCE(q.questions, '[]')::JSONB AS questions,
    COALESCE(a.group_ids, '{}')::UUID[] AS group_ids
FROM quiz.info AS i
LEFT JOIN LATERAL (
    SELECT json_agg(
        json_build_object(
            'id', q.id,
            'title', q.title,
            'score', q.score,
            'type', q.type,
            'single_correct', COALESCE(s.correct, '')::TEXT,
            'single_options', COALESCE(s.options, '{}')::TEXT[],
            'multiple_correct', COALESCE(m.correct, '{}')::TEXT[],
            'multiple_options', COALESCE(m.options, '{}')::TEXT[],
            'numeric_correct', COALESCE(n.correct, 0)::FLOAT
        )
    ) AS questions
    FROM quiz.question AS q
    LEFT JOIN quiz.question_single AS s ON s.question_id = q.id
    LEFT JOIN quiz.question_multiple AS m ON m.question_id = q.id
    LEFT JOIN quiz.question_numeric AS n ON n.question_id = q.id
    WHERE q.quiz_id = i.quiz_id
) AS q ON true
LEFT JOIN LATERAL (
    SELECT array_agg(a.group_id)::UUID[] AS group_ids
    FROM quiz.assignment AS a
    WHERE a.quiz_id = i.quiz_id 
) AS a ON true
WHERE i.quiz_id = $1
`

type GetDomainQuizRow struct {
	QuizID      uuid.UUID       `db:"quiz_id" json:"quiz_id"`
	Title       string          `db:"title" json:"title"`
	Summary     string          `db:"summary" json:"summary"`
	OwnerID     uuid.UUID       `db:"owner_id" json:"owner_id"`
	SubjectID   uuid.UUID       `db:"subject_id" json:"subject_id"`
	MaxAttempts int32           `db:"max_attempts" json:"max_attempts"`
	Deadline    sql.NullTime    `db:"deadline" json:"deadline"`
	TotalScore  int             `db:"total_score" json:"total_score"`
	CreatedAt   time.Time       `db:"created_at" json:"created_at"`
	Questions   json.RawMessage `db:"questions" json:"questions"`
	GroupIds    []uuid.UUID     `db:"group_ids" json:"group_ids"`
}

func (q *Queries) GetDomainQuiz(ctx context.Context, quizID uuid.UUID) (GetDomainQuizRow, error) {
	row := q.db.QueryRowContext(ctx, getDomainQuiz, quizID)
	var i GetDomainQuizRow
	err := row.Scan(
		&i.QuizID,
		&i.Title,
		&i.Summary,
		&i.OwnerID,
		&i.SubjectID,
		&i.MaxAttempts,
		&i.Deadline,
		&i.TotalScore,
		&i.CreatedAt,
		&i.Questions,
		pq.Array(&i.GroupIds),
	)
	return i, err
}

const getDomainQuizzes = `-- name: GetDomainQuizzes :many
SELECT 
    i.quiz_id,
    i.title,
    i.summary,
    i.owner_id,
    i.subject_id,
    i.max_attempts,
    i.deadline,
    i.total_score,
    i.created_at,
    COALESCE(a.group_ids, '{}')::UUID[] AS group_ids
FROM quiz.info AS i
LEFT JOIN LATERAL (
    SELECT array_agg(a.group_id)::UUID[] AS group_ids
    FROM quiz.assignment AS a
    WHERE a.quiz_id = i.quiz_id 
) AS a ON true
`

type GetDomainQuizzesRow struct {
	QuizID      uuid.UUID    `db:"quiz_id" json:"quiz_id"`
	Title       string       `db:"title" json:"title"`
	Summary     string       `db:"summary" json:"summary"`
	OwnerID     uuid.UUID    `db:"owner_id" json:"owner_id"`
	SubjectID   uuid.UUID    `db:"subject_id" json:"subject_id"`
	MaxAttempts int32        `db:"max_attempts" json:"max_attempts"`
	Deadline    sql.NullTime `db:"deadline" json:"deadline"`
	TotalScore  int          `db:"total_score" json:"total_score"`
	CreatedAt   time.Time    `db:"created_at" json:"created_at"`
	GroupIds    []uuid.UUID  `db:"group_ids" json:"group_ids"`
}

func (q *Queries) GetDomainQuizzes(ctx context.Context) ([]GetDomainQuizzesRow, error) {
	rows, err := q.db.QueryContext(ctx, getDomainQuizzes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetDomainQuizzesRow
	for rows.Next() {
		var i GetDomainQuizzesRow
		if err := rows.Scan(
			&i.QuizID,
			&i.Title,
			&i.Summary,
			&i.OwnerID,
			&i.SubjectID,
			&i.MaxAttempts,
			&i.Deadline,
			&i.TotalScore,
			&i.CreatedAt,
			pq.Array(&i.GroupIds),
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDomainSubject = `-- name: GetDomainSubject :one
SELECT 
    s.id,
    s.name
FROM school.subject AS s
WHERE s.id = $1
`

func (q *Queries) GetDomainSubject(ctx context.Context, id uuid.UUID) (SchoolSubject, error) {
	row := q.db.QueryRowContext(ctx, getDomainSubject, id)
	var i SchoolSubject
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}

const getDomainTeacher = `-- name: GetDomainTeacher :one
SELECT
    p.account_id,
    p.first_name,
    p.last_name,
    p.role,
    p.created_at,
    array_agg(t.group_id)::UUID[] AS group_ids
FROM account.profile AS p
LEFT JOIN account.teacher AS t
    ON t.account_id = p.account_id
WHERE p.account_id = $1
GROUP BY
    p.account_id,
    p.first_name,
    p.last_name,
    p.role,
    p.created_at
`

type GetDomainTeacherRow struct {
	AccountID uuid.UUID       `db:"account_id" json:"account_id"`
	FirstName string          `db:"first_name" json:"first_name"`
	LastName  string          `db:"last_name" json:"last_name"`
	Role      AccountUserRole `db:"role" json:"role"`
	CreatedAt time.Time       `db:"created_at" json:"created_at"`
	GroupIds  []uuid.UUID     `db:"group_ids" json:"group_ids"`
}

func (q *Queries) GetDomainTeacher(ctx context.Context, accountID uuid.UUID) (GetDomainTeacherRow, error) {
	row := q.db.QueryRowContext(ctx, getDomainTeacher, accountID)
	var i GetDomainTeacherRow
	err := row.Scan(
		&i.AccountID,
		&i.FirstName,
		&i.LastName,
		&i.Role,
		&i.CreatedAt,
		pq.Array(&i.GroupIds),
	)
	return i, err
}

const getDomainUser = `-- name: GetDomainUser :one
SELECT
    p.account_id,
    p.first_name,
    p.last_name,
    p.role,
    p.created_at
FROM account.profile AS p
WHERE p.account_id = $1
`

func (q *Queries) GetDomainUser(ctx context.Context, accountID uuid.UUID) (AccountProfile, error) {
	row := q.db.QueryRowContext(ctx, getDomainUser, accountID)
	var i AccountProfile
	err := row.Scan(
		&i.AccountID,
		&i.FirstName,
		&i.LastName,
		&i.Role,
		&i.CreatedAt,
	)
	return i, err
}

const getDomainUserByCredential = `-- name: GetDomainUserByCredential :one
SELECT
    p.account_id,
    p.first_name,
    p.last_name,
    p.role,
    p.created_at
FROM account.profile AS p
JOIN account.credential AS c
    ON c.account_id = p.account_id
WHERE 
    c.email = $1 AND c.pwd_hash = $2
`

type GetDomainUserByCredentialParams struct {
	Email   string `db:"email" json:"email"`
	PwdHash string `db:"pwd_hash" json:"pwd_hash"`
}

func (q *Queries) GetDomainUserByCredential(ctx context.Context, arg GetDomainUserByCredentialParams) (AccountProfile, error) {
	row := q.db.QueryRowContext(ctx, getDomainUserByCredential, arg.Email, arg.PwdHash)
	var i AccountProfile
	err := row.Scan(
		&i.AccountID,
		&i.FirstName,
		&i.LastName,
		&i.Role,
		&i.CreatedAt,
	)
	return i, err
}

const listDomainUser = `-- name: ListDomainUser :many
SELECT
    p.account_id,
    p.first_name,
    p.last_name,
    p.role,
    p.created_at
FROM account.profile AS p
WHERE p.account_id = ANY($1::UUID[])
`

func (q *Queries) ListDomainUser(ctx context.Context, dollar_1 []uuid.UUID) ([]AccountProfile, error) {
	rows, err := q.db.QueryContext(ctx, listDomainUser, pq.Array(dollar_1))
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AccountProfile
	for rows.Next() {
		var i AccountProfile
		if err := rows.Scan(
			&i.AccountID,
			&i.FirstName,
			&i.LastName,
			&i.Role,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
