// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: domain.sql

package sqlc

import (
	"context"
	"database/sql"
	"encoding/json"
	"time"

	"github.com/google/uuid"
	"github.com/lib/pq"
)

const getDomainAttempt = `-- name: GetDomainAttempt :one
SELECT 
    attempt.id AS attempt_id,
    attempt.quiz_id AS attempt_quiz_id,
    attempt.user_id AS attempt_user_id,
    attempt.score::INT AS attempt_score_id,
    attempt.started_at AS attempt_started_at,
    attempt.ended_at AS attempt_endend_at,
    json_agg(answer.*) AS attempt_answers
FROM quiz.attempt AS attempt
JOIN quiz.answer AS answer
    ON answer.attempt_id = attempt.id
GROUP BY 
	attempt.id,
	attempt.quiz_id,
    attempt.user_id,
    attempt.score,
    attempt.started_at,
    attempt.ended_at
`

type GetDomainAttemptRow struct {
	AttemptID        uuid.UUID       `db:"attempt_id" json:"attempt_id"`
	AttemptQuizID    uuid.UUID       `db:"attempt_quiz_id" json:"attempt_quiz_id"`
	AttemptUserID    uuid.UUID       `db:"attempt_user_id" json:"attempt_user_id"`
	AttemptScoreID   int32           `db:"attempt_score_id" json:"attempt_score_id"`
	AttemptStartedAt time.Time       `db:"attempt_started_at" json:"attempt_started_at"`
	AttemptEndendAt  sql.NullTime    `db:"attempt_endend_at" json:"attempt_endend_at"`
	AttemptAnswers   json.RawMessage `db:"attempt_answers" json:"attempt_answers"`
}

func (q *Queries) GetDomainAttempt(ctx context.Context) (GetDomainAttemptRow, error) {
	row := q.db.QueryRowContext(ctx, getDomainAttempt)
	var i GetDomainAttemptRow
	err := row.Scan(
		&i.AttemptID,
		&i.AttemptQuizID,
		&i.AttemptUserID,
		&i.AttemptScoreID,
		&i.AttemptStartedAt,
		&i.AttemptEndendAt,
		&i.AttemptAnswers,
	)
	return i, err
}

const getDomainGroup = `-- name: GetDomainGroup :one
SELECT
    g.id,
    g.name,
    t.account_id AS curator_id,
    array_agg(s.account_id)::UUID[] AS student_ids
FROM school.group AS g
LEFT JOIN account.teacher AS t
    ON t.group_id = g.id
LEFT JOIN account.student AS s
    ON s.group_id = g.id
WHERE g.id = $1
GROUP BY g.id, g.name, t.account_id
`

type GetDomainGroupRow struct {
	ID         uuid.UUID     `db:"id" json:"id"`
	Name       string        `db:"name" json:"name"`
	CuratorID  uuid.NullUUID `db:"curator_id" json:"curator_id"`
	StudentIds []uuid.UUID   `db:"student_ids" json:"student_ids"`
}

func (q *Queries) GetDomainGroup(ctx context.Context, id uuid.UUID) (GetDomainGroupRow, error) {
	row := q.db.QueryRowContext(ctx, getDomainGroup, id)
	var i GetDomainGroupRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CuratorID,
		pq.Array(&i.StudentIds),
	)
	return i, err
}

const getDomainQuiz = `-- name: GetDomainQuiz :one
SELECT 
	i.quiz_id AS quiz_id,
	i.title AS quiz_title,
	i.summary AS quiz_summary,
	i.owner_id AS quiz_owner_id,
	i.subject_id AS quiz_subject_id,
	i.total_score::INT AS quiz_total_score,
	i.deadline AS quiz_deadline,
	i.max_attempts::INT AS quiz_max_attempts,
	i.created_at AS quiz_created_at,
	json_agg(q.*)::JSONB AS quiz_questions
FROM quiz.info AS i
JOIN quiz.question AS q
	ON q.quiz_id = i.quiz_id
WHERE i.quiz_id = $1
GROUP BY 
    i.quiz_id,
    i.title,
    i.summary,
    i.owner_id,
    i.subject_id,
    i.total_score,
    i.deadline,
    i.max_attempts,
    i.created_at
`

type GetDomainQuizRow struct {
	QuizID          uuid.UUID       `db:"quiz_id" json:"quiz_id"`
	QuizTitle       string          `db:"quiz_title" json:"quiz_title"`
	QuizSummary     string          `db:"quiz_summary" json:"quiz_summary"`
	QuizOwnerID     uuid.UUID       `db:"quiz_owner_id" json:"quiz_owner_id"`
	QuizSubjectID   uuid.UUID       `db:"quiz_subject_id" json:"quiz_subject_id"`
	QuizTotalScore  int32           `db:"quiz_total_score" json:"quiz_total_score"`
	QuizDeadline    sql.NullTime    `db:"quiz_deadline" json:"quiz_deadline"`
	QuizMaxAttempts int32           `db:"quiz_max_attempts" json:"quiz_max_attempts"`
	QuizCreatedAt   time.Time       `db:"quiz_created_at" json:"quiz_created_at"`
	QuizQuestions   json.RawMessage `db:"quiz_questions" json:"quiz_questions"`
}

func (q *Queries) GetDomainQuiz(ctx context.Context, quizID uuid.UUID) (GetDomainQuizRow, error) {
	row := q.db.QueryRowContext(ctx, getDomainQuiz, quizID)
	var i GetDomainQuizRow
	err := row.Scan(
		&i.QuizID,
		&i.QuizTitle,
		&i.QuizSummary,
		&i.QuizOwnerID,
		&i.QuizSubjectID,
		&i.QuizTotalScore,
		&i.QuizDeadline,
		&i.QuizMaxAttempts,
		&i.QuizCreatedAt,
		&i.QuizQuestions,
	)
	return i, err
}

const getDomainSubject = `-- name: GetDomainSubject :one
SELECT 
    s.id,
    s.name
FROM school.subject AS s
WHERE s.id = $1
`

func (q *Queries) GetDomainSubject(ctx context.Context, id uuid.UUID) (SchoolSubject, error) {
	row := q.db.QueryRowContext(ctx, getDomainSubject, id)
	var i SchoolSubject
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}

const getDomainTeacher = `-- name: GetDomainTeacher :one
SELECT
    p.account_id,
    p.first_name,
    p.last_name,
    p.role,
    p.created_at,
    array_agg(t.group_id)::UUID[] AS group_ids
FROM account.profile AS p
LEFT JOIN account.teacher AS t
    ON t.account_id = p.account_id
WHERE p.account_id = $1
GROUP BY
    p.account_id,
    p.first_name,
    p.last_name,
    p.role,
    p.created_at
`

type GetDomainTeacherRow struct {
	AccountID uuid.UUID       `db:"account_id" json:"account_id"`
	FirstName string          `db:"first_name" json:"first_name"`
	LastName  string          `db:"last_name" json:"last_name"`
	Role      AccountUserRole `db:"role" json:"role"`
	CreatedAt time.Time       `db:"created_at" json:"created_at"`
	GroupIds  []uuid.UUID     `db:"group_ids" json:"group_ids"`
}

func (q *Queries) GetDomainTeacher(ctx context.Context, accountID uuid.UUID) (GetDomainTeacherRow, error) {
	row := q.db.QueryRowContext(ctx, getDomainTeacher, accountID)
	var i GetDomainTeacherRow
	err := row.Scan(
		&i.AccountID,
		&i.FirstName,
		&i.LastName,
		&i.Role,
		&i.CreatedAt,
		pq.Array(&i.GroupIds),
	)
	return i, err
}

const getDomainUser = `-- name: GetDomainUser :one
SELECT
    p.account_id,
    p.first_name,
    p.last_name,
    p.role,
    p.created_at
FROM account.profile AS p
WHERE p.account_id = $1
`

func (q *Queries) GetDomainUser(ctx context.Context, accountID uuid.UUID) (AccountProfile, error) {
	row := q.db.QueryRowContext(ctx, getDomainUser, accountID)
	var i AccountProfile
	err := row.Scan(
		&i.AccountID,
		&i.FirstName,
		&i.LastName,
		&i.Role,
		&i.CreatedAt,
	)
	return i, err
}

const getDomainUserByCredential = `-- name: GetDomainUserByCredential :one
SELECT
    p.account_id,
    p.first_name,
    p.last_name,
    p.role,
    p.created_at
FROM account.profile AS p
JOIN account.credential AS c
    ON c.account_id = p.account_id
WHERE 
    c.email = $1 AND c.pwd_hash = $2
`

type GetDomainUserByCredentialParams struct {
	Email   string `db:"email" json:"email"`
	PwdHash string `db:"pwd_hash" json:"pwd_hash"`
}

func (q *Queries) GetDomainUserByCredential(ctx context.Context, arg GetDomainUserByCredentialParams) (AccountProfile, error) {
	row := q.db.QueryRowContext(ctx, getDomainUserByCredential, arg.Email, arg.PwdHash)
	var i AccountProfile
	err := row.Scan(
		&i.AccountID,
		&i.FirstName,
		&i.LastName,
		&i.Role,
		&i.CreatedAt,
	)
	return i, err
}

const listDomainUser = `-- name: ListDomainUser :many
SELECT
    p.account_id,
    p.first_name,
    p.last_name,
    p.role,
    p.created_at
FROM account.profile AS p
WHERE p.account_id IN ($1::UUID[])
`

func (q *Queries) ListDomainUser(ctx context.Context, dollar_1 []uuid.UUID) ([]AccountProfile, error) {
	rows, err := q.db.QueryContext(ctx, listDomainUser, pq.Array(dollar_1))
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AccountProfile
	for rows.Next() {
		var i AccountProfile
		if err := rows.Scan(
			&i.AccountID,
			&i.FirstName,
			&i.LastName,
			&i.Role,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
