// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: dto.sql

package sqlc

import (
	"context"
	"database/sql"
	"encoding/json"
	"time"

	"github.com/google/uuid"
	"github.com/lib/pq"
)

const getDetailedUsers = `-- name: GetDetailedUsers :many
SELECT 
	p.account_id, 
	p.first_name, 
	p.last_name, 
	p.role, 
	p.created_at,
	s.group_id AS s_group_id,
	array_remove(array_agg(t.group_id), NULL)::UUID[] AS t_group_ids
FROM account.profile AS p
LEFT JOIN account.student AS s
	ON s.account_id = p.account_id
LEFT JOIN account.teacher AS t
	ON t.account_id = p.account_id
GROUP BY 
	p.account_id, 
	p.first_name,
	p.last_name,
	p.role,
	p.created_at,
	s.group_id
`

type GetDetailedUsersRow struct {
	AccountID uuid.UUID       `db:"account_id" json:"account_id"`
	FirstName string          `db:"first_name" json:"first_name"`
	LastName  string          `db:"last_name" json:"last_name"`
	Role      AccountUserRole `db:"role" json:"role"`
	CreatedAt time.Time       `db:"created_at" json:"created_at"`
	SGroupID  uuid.NullUUID   `db:"s_group_id" json:"s_group_id"`
	TGroupIds []uuid.UUID     `db:"t_group_ids" json:"t_group_ids"`
}

func (q *Queries) GetDetailedUsers(ctx context.Context) ([]GetDetailedUsersRow, error) {
	rows, err := q.db.QueryContext(ctx, getDetailedUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetDetailedUsersRow
	for rows.Next() {
		var i GetDetailedUsersRow
		if err := rows.Scan(
			&i.AccountID,
			&i.FirstName,
			&i.LastName,
			&i.Role,
			&i.CreatedAt,
			&i.SGroupID,
			pq.Array(&i.TGroupIds),
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getFinishedAttempt = `-- name: GetFinishedAttempt :one
SELECT 
    attempt.id AS attempt_id,
    attempt.score::INT AS attempt_score,
    attempt.started_at AS attempt_started_at,
    attempt.ended_at AS attempt_ended_at,
    (
		SELECT json_agg(answer.*) 
		FROM quiz.answer 
		WHERE attempt_id = $1
	) AS attempt_answers,

    a_user.account_id AS user_id,
    a_user.first_name AS user_first_name,
    a_user.last_name AS user_last_name,
    a_user.role AS user_role,
    a_user.created_at AS user_created_at,

    q_info.quiz_id AS quiz_id,
    q_info.title AS quiz_title,
    q_info.summary AS quiz_summary,
    q_info.total_score::INT AS quiz_total_score,
    q_info.deadline AS quiz_deadline,
    q_info.max_attempts AS quiz_max_attempts,
    q_info.created_at AS quiz_created_at,
    (
		SELECT json_agg(question.*)
		FROM quiz.question
		WHERE quiz_id = q_info.quiz_id
	)AS quiz_questions,

    q_owner.account_id AS owner_id,
    q_owner.first_name AS owner_first_name,
    q_owner.last_name AS owner_last_name,
    q_owner.role AS owner_role,
    q_owner.created_at AS owner_created_at,

    q_subject.id AS subject_id,
    q_subject.name AS subject_name

FROM quiz.attempt AS attempt

JOIN account.profile AS a_user 
    ON a_user.account_id = attempt.user_id

JOIN quiz.info AS q_info
    ON q_info.quiz_id = attempt.quiz_id

JOIN account.profile AS q_owner 
    ON q_owner.account_id = q_info.owner_id
    
JOIN school.subject AS q_subject
    ON q_subject.id = q_info.subject_id

WHERE attempt.id = $1
`

type GetFinishedAttemptRow struct {
	AttemptID        uuid.UUID       `db:"attempt_id" json:"attempt_id"`
	AttemptScore     int32           `db:"attempt_score" json:"attempt_score"`
	AttemptStartedAt time.Time       `db:"attempt_started_at" json:"attempt_started_at"`
	AttemptEndedAt   sql.NullTime    `db:"attempt_ended_at" json:"attempt_ended_at"`
	AttemptAnswers   json.RawMessage `db:"attempt_answers" json:"attempt_answers"`
	UserID           uuid.UUID       `db:"user_id" json:"user_id"`
	UserFirstName    string          `db:"user_first_name" json:"user_first_name"`
	UserLastName     string          `db:"user_last_name" json:"user_last_name"`
	UserRole         AccountUserRole `db:"user_role" json:"user_role"`
	UserCreatedAt    time.Time       `db:"user_created_at" json:"user_created_at"`
	QuizID           uuid.UUID       `db:"quiz_id" json:"quiz_id"`
	QuizTitle        string          `db:"quiz_title" json:"quiz_title"`
	QuizSummary      string          `db:"quiz_summary" json:"quiz_summary"`
	QuizTotalScore   int32           `db:"quiz_total_score" json:"quiz_total_score"`
	QuizDeadline     sql.NullTime    `db:"quiz_deadline" json:"quiz_deadline"`
	QuizMaxAttempts  int32           `db:"quiz_max_attempts" json:"quiz_max_attempts"`
	QuizCreatedAt    time.Time       `db:"quiz_created_at" json:"quiz_created_at"`
	QuizQuestions    json.RawMessage `db:"quiz_questions" json:"quiz_questions"`
	OwnerID          uuid.UUID       `db:"owner_id" json:"owner_id"`
	OwnerFirstName   string          `db:"owner_first_name" json:"owner_first_name"`
	OwnerLastName    string          `db:"owner_last_name" json:"owner_last_name"`
	OwnerRole        AccountUserRole `db:"owner_role" json:"owner_role"`
	OwnerCreatedAt   time.Time       `db:"owner_created_at" json:"owner_created_at"`
	SubjectID        uuid.UUID       `db:"subject_id" json:"subject_id"`
	SubjectName      string          `db:"subject_name" json:"subject_name"`
}

func (q *Queries) GetFinishedAttempt(ctx context.Context, attemptID uuid.UUID) (GetFinishedAttemptRow, error) {
	row := q.db.QueryRowContext(ctx, getFinishedAttempt, attemptID)
	var i GetFinishedAttemptRow
	err := row.Scan(
		&i.AttemptID,
		&i.AttemptScore,
		&i.AttemptStartedAt,
		&i.AttemptEndedAt,
		&i.AttemptAnswers,
		&i.UserID,
		&i.UserFirstName,
		&i.UserLastName,
		&i.UserRole,
		&i.UserCreatedAt,
		&i.QuizID,
		&i.QuizTitle,
		&i.QuizSummary,
		&i.QuizTotalScore,
		&i.QuizDeadline,
		&i.QuizMaxAttempts,
		&i.QuizCreatedAt,
		&i.QuizQuestions,
		&i.OwnerID,
		&i.OwnerFirstName,
		&i.OwnerLastName,
		&i.OwnerRole,
		&i.OwnerCreatedAt,
		&i.SubjectID,
		&i.SubjectName,
	)
	return i, err
}

const getQuiz = `-- name: GetQuiz :one
SELECT 
	i.quiz_id AS quiz_id, 
	i.title AS quiz_title,
	i.summary AS quiz_summary,
	i.total_score::INT AS quiz_total_score,
	i.deadline AS quiz_deadline,
	i.max_attempts AS quiz_max_attempts,
	i.created_at AS quiz_created_at,
    json_agg(q.*)::JSONB AS quiz_questions,
	p.account_id AS owner_id,
	p.first_name AS owner_first_name,
	p.last_name AS owner_last_name,
	p.role AS owner_role,
	p.created_at AS owner_created_at,
	s.id AS subject_id,
	s.name AS subject_name
FROM quiz.info AS i
JOIN quiz.question AS q
    ON q.quiz_id = i.quiz_id
JOIN account.profile AS p 
	ON p.account_id = i.owner_id
JOIN school.subject AS s
	ON s.id = i.subject_id
WHERE i.quiz_id = $1
GROUP BY
	i.quiz_id, 
	i.title,
	i.summary,
	i.total_score,
	i.deadline,
	i.max_attempts,
	i.created_at,
	p.account_id,
	p.first_name,
	p.last_name ,
	p.role,
	p.created_at,
	s.id,
	s.name
`

type GetQuizRow struct {
	QuizID          uuid.UUID       `db:"quiz_id" json:"quiz_id"`
	QuizTitle       string          `db:"quiz_title" json:"quiz_title"`
	QuizSummary     string          `db:"quiz_summary" json:"quiz_summary"`
	QuizTotalScore  int32           `db:"quiz_total_score" json:"quiz_total_score"`
	QuizDeadline    sql.NullTime    `db:"quiz_deadline" json:"quiz_deadline"`
	QuizMaxAttempts int32           `db:"quiz_max_attempts" json:"quiz_max_attempts"`
	QuizCreatedAt   time.Time       `db:"quiz_created_at" json:"quiz_created_at"`
	QuizQuestions   json.RawMessage `db:"quiz_questions" json:"quiz_questions"`
	OwnerID         uuid.UUID       `db:"owner_id" json:"owner_id"`
	OwnerFirstName  string          `db:"owner_first_name" json:"owner_first_name"`
	OwnerLastName   string          `db:"owner_last_name" json:"owner_last_name"`
	OwnerRole       AccountUserRole `db:"owner_role" json:"owner_role"`
	OwnerCreatedAt  time.Time       `db:"owner_created_at" json:"owner_created_at"`
	SubjectID       uuid.UUID       `db:"subject_id" json:"subject_id"`
	SubjectName     string          `db:"subject_name" json:"subject_name"`
}

func (q *Queries) GetQuiz(ctx context.Context, quizID uuid.UUID) (GetQuizRow, error) {
	row := q.db.QueryRowContext(ctx, getQuiz, quizID)
	var i GetQuizRow
	err := row.Scan(
		&i.QuizID,
		&i.QuizTitle,
		&i.QuizSummary,
		&i.QuizTotalScore,
		&i.QuizDeadline,
		&i.QuizMaxAttempts,
		&i.QuizCreatedAt,
		&i.QuizQuestions,
		&i.OwnerID,
		&i.OwnerFirstName,
		&i.OwnerLastName,
		&i.OwnerRole,
		&i.OwnerCreatedAt,
		&i.SubjectID,
		&i.SubjectName,
	)
	return i, err
}

const getQuizItem = `-- name: GetQuizItem :many
SELECT 
	i.quiz_id AS quiz_id, 
	i.title AS quiz_title,
	i.summary AS quiz_summary,
	i.total_score::INT AS quiz_total_score,
	i.created_at AS quiz_created_at,
    i.deadline AS quiz_deadline,
    i.max_attempts::INT AS quiz_max_attempts,
	p.account_id AS owner_id,
	p.first_name AS owner_first_name,
	p.last_name AS owner_last_name,
	p.role AS owner_role,
	p.created_at AS owner_created_at,
	s.id AS subject_id,
	s.name AS subject_name
FROM quiz.info AS i
JOIN account.profile AS p
	ON p.account_id = i.owner_id
JOIN school.subject AS s
	ON s.id = i.subject_id
`

type GetQuizItemRow struct {
	QuizID          uuid.UUID       `db:"quiz_id" json:"quiz_id"`
	QuizTitle       string          `db:"quiz_title" json:"quiz_title"`
	QuizSummary     string          `db:"quiz_summary" json:"quiz_summary"`
	QuizTotalScore  int32           `db:"quiz_total_score" json:"quiz_total_score"`
	QuizCreatedAt   time.Time       `db:"quiz_created_at" json:"quiz_created_at"`
	QuizDeadline    sql.NullTime    `db:"quiz_deadline" json:"quiz_deadline"`
	QuizMaxAttempts int32           `db:"quiz_max_attempts" json:"quiz_max_attempts"`
	OwnerID         uuid.UUID       `db:"owner_id" json:"owner_id"`
	OwnerFirstName  string          `db:"owner_first_name" json:"owner_first_name"`
	OwnerLastName   string          `db:"owner_last_name" json:"owner_last_name"`
	OwnerRole       AccountUserRole `db:"owner_role" json:"owner_role"`
	OwnerCreatedAt  time.Time       `db:"owner_created_at" json:"owner_created_at"`
	SubjectID       uuid.UUID       `db:"subject_id" json:"subject_id"`
	SubjectName     string          `db:"subject_name" json:"subject_name"`
}

func (q *Queries) GetQuizItem(ctx context.Context) ([]GetQuizItemRow, error) {
	rows, err := q.db.QueryContext(ctx, getQuizItem)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetQuizItemRow
	for rows.Next() {
		var i GetQuizItemRow
		if err := rows.Scan(
			&i.QuizID,
			&i.QuizTitle,
			&i.QuizSummary,
			&i.QuizTotalScore,
			&i.QuizCreatedAt,
			&i.QuizDeadline,
			&i.QuizMaxAttempts,
			&i.OwnerID,
			&i.OwnerFirstName,
			&i.OwnerLastName,
			&i.OwnerRole,
			&i.OwnerCreatedAt,
			&i.SubjectID,
			&i.SubjectName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
