// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"database/sql"
	"database/sql/driver"
	"encoding/json"
	"fmt"
	"time"

	"github.com/google/uuid"
)

type AccountUserRole string

const (
	AccountUserRoleTeacher AccountUserRole = "teacher"
	AccountUserRoleStudent AccountUserRole = "student"
	AccountUserRoleAdmin   AccountUserRole = "admin"
)

func (e *AccountUserRole) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = AccountUserRole(s)
	case string:
		*e = AccountUserRole(s)
	default:
		return fmt.Errorf("unsupported scan type for AccountUserRole: %T", src)
	}
	return nil
}

type NullAccountUserRole struct {
	AccountUserRole AccountUserRole
	Valid           bool // Valid is true if AccountUserRole is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullAccountUserRole) Scan(value interface{}) error {
	if value == nil {
		ns.AccountUserRole, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.AccountUserRole.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullAccountUserRole) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.AccountUserRole), nil
}

type QuizQuestionType string

const (
	QuizQuestionTypeSingle   QuizQuestionType = "single"
	QuizQuestionTypeMultiple QuizQuestionType = "multiple"
	QuizQuestionTypeNumeric  QuizQuestionType = "numeric"
)

func (e *QuizQuestionType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = QuizQuestionType(s)
	case string:
		*e = QuizQuestionType(s)
	default:
		return fmt.Errorf("unsupported scan type for QuizQuestionType: %T", src)
	}
	return nil
}

type NullQuizQuestionType struct {
	QuizQuestionType QuizQuestionType
	Valid            bool // Valid is true if QuizQuestionType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullQuizQuestionType) Scan(value interface{}) error {
	if value == nil {
		ns.QuizQuestionType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.QuizQuestionType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullQuizQuestionType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.QuizQuestionType), nil
}

type AccountCredential struct {
	AccountID uuid.UUID
	Email     string
	PwdHash   string
}

type AccountProfile struct {
	AccountID uuid.UUID
	FirstName string
	LastName  string
	Role      AccountUserRole
	CreatedAt time.Time
}

type AccountStudent struct {
	AccountID uuid.UUID
	GroupID   uuid.UUID
}

type AccountTeacher struct {
	AccountID uuid.UUID
	GroupID   uuid.UUID
	SubjectID uuid.UUID
}

type QuizAnswer struct {
	ID         uuid.UUID
	AttemptID  uuid.UUID
	QuestionID uuid.UUID
	Score      interface{}
	IsCorrect  bool
}

type QuizAttempt struct {
	ID        uuid.UUID
	QuizID    uuid.UUID
	UserID    uuid.UUID
	Content   json.RawMessage
	Score     interface{}
	StartedAt time.Time
	EndedAt   sql.NullTime
}

type QuizInfo struct {
	QuizID      uuid.UUID
	Title       string
	Summary     string
	SubjectID   uuid.UUID
	OwnerID     uuid.UUID
	MaxAttempts int32
	TotalScore  interface{}
	Deadline    sql.NullTime
	CreatedAt   time.Time
}

type QuizQuestion struct {
	ID      uuid.UUID
	QuizID  uuid.UUID
	Variant QuizQuestionType
	Score   interface{}
	Details json.RawMessage
}

type SchoolGroup struct {
	ID   uuid.UUID
	Name string
}

type SchoolSubject struct {
	ID   uuid.UUID
	Name string
}
