// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"database/sql"
	"database/sql/driver"
	"encoding/json"
	"fmt"
	"time"

	"github.com/google/uuid"
)

type AccountUserRole string

const (
	AccountUserRoleTeacher AccountUserRole = "teacher"
	AccountUserRoleStudent AccountUserRole = "student"
	AccountUserRoleAdmin   AccountUserRole = "admin"
)

func (e *AccountUserRole) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = AccountUserRole(s)
	case string:
		*e = AccountUserRole(s)
	default:
		return fmt.Errorf("unsupported scan type for AccountUserRole: %T", src)
	}
	return nil
}

type NullAccountUserRole struct {
	AccountUserRole AccountUserRole `json:"account_user_role"`
	Valid           bool            `json:"valid"` // Valid is true if AccountUserRole is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullAccountUserRole) Scan(value interface{}) error {
	if value == nil {
		ns.AccountUserRole, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.AccountUserRole.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullAccountUserRole) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.AccountUserRole), nil
}

type QuizQuestionType string

const (
	QuizQuestionTypeSingle   QuizQuestionType = "single"
	QuizQuestionTypeMultiple QuizQuestionType = "multiple"
	QuizQuestionTypeNumeric  QuizQuestionType = "numeric"
)

func (e *QuizQuestionType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = QuizQuestionType(s)
	case string:
		*e = QuizQuestionType(s)
	default:
		return fmt.Errorf("unsupported scan type for QuizQuestionType: %T", src)
	}
	return nil
}

type NullQuizQuestionType struct {
	QuizQuestionType QuizQuestionType `json:"quiz_question_type"`
	Valid            bool             `json:"valid"` // Valid is true if QuizQuestionType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullQuizQuestionType) Scan(value interface{}) error {
	if value == nil {
		ns.QuizQuestionType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.QuizQuestionType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullQuizQuestionType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.QuizQuestionType), nil
}

type AccountCredential struct {
	AccountID uuid.UUID `db:"account_id" json:"account_id"`
	Email     string    `db:"email" json:"email"`
	PwdHash   string    `db:"pwd_hash" json:"pwd_hash"`
}

type AccountProfile struct {
	AccountID uuid.UUID       `db:"account_id" json:"account_id"`
	FirstName string          `db:"first_name" json:"first_name"`
	LastName  string          `db:"last_name" json:"last_name"`
	Role      AccountUserRole `db:"role" json:"role"`
	CreatedAt time.Time       `db:"created_at" json:"created_at"`
}

type AccountStudent struct {
	AccountID uuid.UUID `db:"account_id" json:"account_id"`
	GroupID   uuid.UUID `db:"group_id" json:"group_id"`
}

type AccountTeacher struct {
	AccountID uuid.UUID `db:"account_id" json:"account_id"`
	GroupID   uuid.UUID `db:"group_id" json:"group_id"`
}

type QuizAnswer struct {
	ID         uuid.UUID       `db:"id" json:"id"`
	AttemptID  uuid.UUID       `db:"attempt_id" json:"attempt_id"`
	QuestionID uuid.UUID       `db:"question_id" json:"question_id"`
	Details    json.RawMessage `db:"details" json:"details"`
	Score      int             `db:"score" json:"score"`
	IsCorrect  bool            `db:"is_correct" json:"is_correct"`
}

type QuizAssignment struct {
	QuizID  uuid.UUID `db:"quiz_id" json:"quiz_id"`
	GroupID uuid.UUID `db:"group_id" json:"group_id"`
}

type QuizAttempt struct {
	ID            uuid.UUID    `db:"id" json:"id"`
	NumberAttempt int16        `db:"number_attempt" json:"number_attempt"`
	QuizID        uuid.UUID    `db:"quiz_id" json:"quiz_id"`
	UserID        uuid.UUID    `db:"user_id" json:"user_id"`
	Score         int          `db:"score" json:"score"`
	StartedAt     time.Time    `db:"started_at" json:"started_at"`
	EndedAt       sql.NullTime `db:"ended_at" json:"ended_at"`
}

type QuizInfo struct {
	QuizID      uuid.UUID    `db:"quiz_id" json:"quiz_id"`
	Title       string       `db:"title" json:"title"`
	Summary     string       `db:"summary" json:"summary"`
	SubjectID   uuid.UUID    `db:"subject_id" json:"subject_id"`
	OwnerID     uuid.UUID    `db:"owner_id" json:"owner_id"`
	MaxAttempts int32        `db:"max_attempts" json:"max_attempts"`
	Deadline    sql.NullTime `db:"deadline" json:"deadline"`
	TotalScore  int          `db:"total_score" json:"total_score"`
	CreatedAt   time.Time    `db:"created_at" json:"created_at"`
}

type QuizQuestion struct {
	ID     uuid.UUID   `db:"id" json:"id"`
	QuizID uuid.UUID   `db:"quiz_id" json:"quiz_id"`
	Title  string      `db:"title" json:"title"`
	Score  int         `db:"score" json:"score"`
	Type   interface{} `db:"type" json:"type"`
}

type QuizQuestionMultiple struct {
	QuestionID uuid.UUID `db:"question_id" json:"question_id"`
	Correct    []string  `db:"correct" json:"correct"`
	Options    []string  `db:"options" json:"options"`
}

type QuizQuestionNumeric struct {
	QuestionID uuid.UUID `db:"question_id" json:"question_id"`
	Correct    float64   `db:"correct" json:"correct"`
}

type QuizQuestionSingle struct {
	QuestionID uuid.UUID `db:"question_id" json:"question_id"`
	Correct    string    `db:"correct" json:"correct"`
	Options    []string  `db:"options" json:"options"`
}

type SchoolGroup struct {
	ID   uuid.UUID `db:"id" json:"id"`
	Name string    `db:"name" json:"name"`
}

type SchoolSubject struct {
	ID   uuid.UUID `db:"id" json:"id"`
	Name string    `db:"name" json:"name"`
}
