// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package sqlc

import (
	"context"
	"database/sql"
	"encoding/json"
	"time"

	"github.com/google/uuid"
	"github.com/lib/pq"
)

const getDetailedUsers = `-- name: GetDetailedUsers :many
SELECT 
	p.account_id, 
	p.first_name, 
	p.last_name, 
	p.role, 
	p.created_at,
	s.group_id AS s_group_id,
	array_remove(array_agg(t.group_id), NULL)::UUID[] AS t_group_ids,
	array_remove(array_agg(t.subject_id), NULL)::UUID[] AS t_subject_ids
FROM account.profile AS p
LEFT JOIN account.student AS s
	ON s.account_id = p.account_id
LEFT JOIN account.teacher AS t
	ON t.account_id = p.account_id
GROUP BY 
	p.account_id, 
	p.first_name,
	p.last_name,
	p.role,
	p.created_at,
	s.group_id
`

type GetDetailedUsersRow struct {
	AccountID   uuid.UUID       `db:"account_id" json:"account_id"`
	FirstName   string          `db:"first_name" json:"first_name"`
	LastName    string          `db:"last_name" json:"last_name"`
	Role        AccountUserRole `db:"role" json:"role"`
	CreatedAt   time.Time       `db:"created_at" json:"created_at"`
	SGroupID    uuid.NullUUID   `db:"s_group_id" json:"s_group_id"`
	TGroupIds   []uuid.UUID     `db:"t_group_ids" json:"t_group_ids"`
	TSubjectIds []uuid.UUID     `db:"t_subject_ids" json:"t_subject_ids"`
}

func (q *Queries) GetDetailedUsers(ctx context.Context) ([]GetDetailedUsersRow, error) {
	rows, err := q.db.QueryContext(ctx, getDetailedUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetDetailedUsersRow
	for rows.Next() {
		var i GetDetailedUsersRow
		if err := rows.Scan(
			&i.AccountID,
			&i.FirstName,
			&i.LastName,
			&i.Role,
			&i.CreatedAt,
			&i.SGroupID,
			pq.Array(&i.TGroupIds),
			pq.Array(&i.TSubjectIds),
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDomainAttempt = `-- name: GetDomainAttempt :one
SELECT 
    attempt.id AS attempt_id,
    attempt.quiz_id AS attempt_quiz_id,
    attempt.user_id AS attempt_user_id,
    attempt.score::INT AS attempt_score_id,
    attempt.started_at AS attempt_started_at,
    attempt.ended_at AS attempt_endend_at,
    json_agg(answer.*) AS attempt_answers
FROM quiz.attempt AS attempt
JOIN quiz.answer AS answer
    ON answer.attempt_id = attempt.id
GROUP BY 
	attempt.id,
	attempt.quiz_id,
    attempt.user_id,
    attempt.score,
    attempt.started_at,
    attempt.ended_at
`

type GetDomainAttemptRow struct {
	AttemptID        uuid.UUID       `db:"attempt_id" json:"attempt_id"`
	AttemptQuizID    uuid.UUID       `db:"attempt_quiz_id" json:"attempt_quiz_id"`
	AttemptUserID    uuid.UUID       `db:"attempt_user_id" json:"attempt_user_id"`
	AttemptScoreID   int32           `db:"attempt_score_id" json:"attempt_score_id"`
	AttemptStartedAt time.Time       `db:"attempt_started_at" json:"attempt_started_at"`
	AttemptEndendAt  sql.NullTime    `db:"attempt_endend_at" json:"attempt_endend_at"`
	AttemptAnswers   json.RawMessage `db:"attempt_answers" json:"attempt_answers"`
}

func (q *Queries) GetDomainAttempt(ctx context.Context) (GetDomainAttemptRow, error) {
	row := q.db.QueryRowContext(ctx, getDomainAttempt)
	var i GetDomainAttemptRow
	err := row.Scan(
		&i.AttemptID,
		&i.AttemptQuizID,
		&i.AttemptUserID,
		&i.AttemptScoreID,
		&i.AttemptStartedAt,
		&i.AttemptEndendAt,
		&i.AttemptAnswers,
	)
	return i, err
}

const getDomainQuiz = `-- name: GetDomainQuiz :one
SELECT 
	i.quiz_id AS quiz_id,
	i.title AS quiz_title,
	i.summary AS quiz_summary,
	i.owner_id AS quiz_owner_id,
	i.subject_id AS quiz_subject_id,
	i.total_score::INT AS quiz_total_score,
	i.deadline AS quiz_deadline,
	i.max_attempts::INT AS quiz_max_attempts,
	i.created_at AS quiz_created_at,
	json_agg(q.*)::JSONB AS quiz_questions
FROM quiz.info AS i
JOIN quiz.question AS q
	ON q.quiz_id = i.quiz_id
WHERE i.quiz_id = $1
GROUP BY 
    i.quiz_id,
    i.title,
    i.summary,
    i.owner_id,
    i.subject_id,
    i.total_score,
    i.deadline,
    i.max_attempts,
    i.created_at
`

type GetDomainQuizRow struct {
	QuizID          uuid.UUID       `db:"quiz_id" json:"quiz_id"`
	QuizTitle       string          `db:"quiz_title" json:"quiz_title"`
	QuizSummary     string          `db:"quiz_summary" json:"quiz_summary"`
	QuizOwnerID     uuid.UUID       `db:"quiz_owner_id" json:"quiz_owner_id"`
	QuizSubjectID   uuid.UUID       `db:"quiz_subject_id" json:"quiz_subject_id"`
	QuizTotalScore  int32           `db:"quiz_total_score" json:"quiz_total_score"`
	QuizDeadline    sql.NullTime    `db:"quiz_deadline" json:"quiz_deadline"`
	QuizMaxAttempts int32           `db:"quiz_max_attempts" json:"quiz_max_attempts"`
	QuizCreatedAt   time.Time       `db:"quiz_created_at" json:"quiz_created_at"`
	QuizQuestions   json.RawMessage `db:"quiz_questions" json:"quiz_questions"`
}

func (q *Queries) GetDomainQuiz(ctx context.Context, quizID uuid.UUID) (GetDomainQuizRow, error) {
	row := q.db.QueryRowContext(ctx, getDomainQuiz, quizID)
	var i GetDomainQuizRow
	err := row.Scan(
		&i.QuizID,
		&i.QuizTitle,
		&i.QuizSummary,
		&i.QuizOwnerID,
		&i.QuizSubjectID,
		&i.QuizTotalScore,
		&i.QuizDeadline,
		&i.QuizMaxAttempts,
		&i.QuizCreatedAt,
		&i.QuizQuestions,
	)
	return i, err
}

const getFinishedAttempt = `-- name: GetFinishedAttempt :one
SELECT 
    attempt.id AS attempt_id,
    attempt.score::INT AS attempt_score,
    attempt.started_at AS attempt_started_at,
    attempt.ended_at AS attempt_ended_at,
    (
		SELECT json_agg(answer.*) 
		FROM quiz.answer 
		WHERE attempt_id = $1
	) AS attempt_answers,

    a_user.account_id AS user_id,
    a_user.first_name AS user_first_name,
    a_user.last_name AS user_last_name,
    a_user.role AS user_role,
    a_user.created_at AS user_created_at,

    q_info.quiz_id AS quiz_id,
    q_info.title AS quiz_title,
    q_info.summary AS quiz_summary,
    q_info.total_score::INT AS quiz_total_score,
    q_info.deadline AS quiz_deadline,
    q_info.max_attempts AS quiz_max_attempts,
    q_info.created_at AS quiz_created_at,
    (
		SELECT json_agg(question.*)
		FROM quiz.question
		WHERE quiz_id = q_info.quiz_id
	)AS quiz_questions,

    q_owner.account_id AS owner_id,
    q_owner.first_name AS owner_first_name,
    q_owner.last_name AS owner_last_name,
    q_owner.role AS owner_role,
    q_owner.created_at AS owner_created_at,

    q_subject.id AS subject_id,
    q_subject.name AS subject_name

FROM quiz.attempt AS attempt

JOIN account.profile AS a_user 
    ON a_user.account_id = attempt.user_id

JOIN quiz.info AS q_info
    ON q_info.quiz_id = attempt.quiz_id

JOIN account.profile AS q_owner 
    ON q_owner.account_id = q_info.owner_id
    
JOIN school.subject AS q_subject
    ON q_subject.id = q_info.subject_id

WHERE attempt.id = $1
`

type GetFinishedAttemptRow struct {
	AttemptID        uuid.UUID       `db:"attempt_id" json:"attempt_id"`
	AttemptScore     int32           `db:"attempt_score" json:"attempt_score"`
	AttemptStartedAt time.Time       `db:"attempt_started_at" json:"attempt_started_at"`
	AttemptEndedAt   sql.NullTime    `db:"attempt_ended_at" json:"attempt_ended_at"`
	AttemptAnswers   json.RawMessage `db:"attempt_answers" json:"attempt_answers"`
	UserID           uuid.UUID       `db:"user_id" json:"user_id"`
	UserFirstName    string          `db:"user_first_name" json:"user_first_name"`
	UserLastName     string          `db:"user_last_name" json:"user_last_name"`
	UserRole         AccountUserRole `db:"user_role" json:"user_role"`
	UserCreatedAt    time.Time       `db:"user_created_at" json:"user_created_at"`
	QuizID           uuid.UUID       `db:"quiz_id" json:"quiz_id"`
	QuizTitle        string          `db:"quiz_title" json:"quiz_title"`
	QuizSummary      string          `db:"quiz_summary" json:"quiz_summary"`
	QuizTotalScore   int32           `db:"quiz_total_score" json:"quiz_total_score"`
	QuizDeadline     sql.NullTime    `db:"quiz_deadline" json:"quiz_deadline"`
	QuizMaxAttempts  int32           `db:"quiz_max_attempts" json:"quiz_max_attempts"`
	QuizCreatedAt    time.Time       `db:"quiz_created_at" json:"quiz_created_at"`
	QuizQuestions    json.RawMessage `db:"quiz_questions" json:"quiz_questions"`
	OwnerID          uuid.UUID       `db:"owner_id" json:"owner_id"`
	OwnerFirstName   string          `db:"owner_first_name" json:"owner_first_name"`
	OwnerLastName    string          `db:"owner_last_name" json:"owner_last_name"`
	OwnerRole        AccountUserRole `db:"owner_role" json:"owner_role"`
	OwnerCreatedAt   time.Time       `db:"owner_created_at" json:"owner_created_at"`
	SubjectID        uuid.UUID       `db:"subject_id" json:"subject_id"`
	SubjectName      string          `db:"subject_name" json:"subject_name"`
}

func (q *Queries) GetFinishedAttempt(ctx context.Context, attemptID uuid.UUID) (GetFinishedAttemptRow, error) {
	row := q.db.QueryRowContext(ctx, getFinishedAttempt, attemptID)
	var i GetFinishedAttemptRow
	err := row.Scan(
		&i.AttemptID,
		&i.AttemptScore,
		&i.AttemptStartedAt,
		&i.AttemptEndedAt,
		&i.AttemptAnswers,
		&i.UserID,
		&i.UserFirstName,
		&i.UserLastName,
		&i.UserRole,
		&i.UserCreatedAt,
		&i.QuizID,
		&i.QuizTitle,
		&i.QuizSummary,
		&i.QuizTotalScore,
		&i.QuizDeadline,
		&i.QuizMaxAttempts,
		&i.QuizCreatedAt,
		&i.QuizQuestions,
		&i.OwnerID,
		&i.OwnerFirstName,
		&i.OwnerLastName,
		&i.OwnerRole,
		&i.OwnerCreatedAt,
		&i.SubjectID,
		&i.SubjectName,
	)
	return i, err
}

const getQuiz = `-- name: GetQuiz :one
SELECT 
	i.quiz_id AS quiz_id, 
	i.title AS quiz_title,
	i.summary AS quiz_summary,
	i.total_score::INT AS quiz_total_score,
	i.deadline AS quiz_deadline,
	i.max_attempts AS quiz_max_attempts,
	i.created_at AS quiz_created_at,
    json_agg(q.*)::JSONB AS quiz_questions,
	p.account_id AS owner_id,
	p.first_name AS owner_first_name,
	p.last_name AS owner_last_name,
	p.role AS owner_role,
	p.created_at AS owner_created_at,
	s.id AS subject_id,
	s.name AS subject_name
FROM quiz.info AS i
JOIN quiz.question AS q
    ON q.quiz_id = i.quiz_id
JOIN account.profile AS p 
	ON p.account_id = i.owner_id
JOIN school.subject AS s
	ON s.id = i.subject_id
WHERE i.quiz_id = $1
GROUP BY
	i.quiz_id, 
	i.title,
	i.summary,
	i.total_score,
	i.deadline,
	i.max_attempts,
	i.created_at,
	p.account_id,
	p.first_name,
	p.last_name ,
	p.role,
	p.created_at,
	s.id,
	s.name
`

type GetQuizRow struct {
	QuizID          uuid.UUID       `db:"quiz_id" json:"quiz_id"`
	QuizTitle       string          `db:"quiz_title" json:"quiz_title"`
	QuizSummary     string          `db:"quiz_summary" json:"quiz_summary"`
	QuizTotalScore  int32           `db:"quiz_total_score" json:"quiz_total_score"`
	QuizDeadline    sql.NullTime    `db:"quiz_deadline" json:"quiz_deadline"`
	QuizMaxAttempts int32           `db:"quiz_max_attempts" json:"quiz_max_attempts"`
	QuizCreatedAt   time.Time       `db:"quiz_created_at" json:"quiz_created_at"`
	QuizQuestions   json.RawMessage `db:"quiz_questions" json:"quiz_questions"`
	OwnerID         uuid.UUID       `db:"owner_id" json:"owner_id"`
	OwnerFirstName  string          `db:"owner_first_name" json:"owner_first_name"`
	OwnerLastName   string          `db:"owner_last_name" json:"owner_last_name"`
	OwnerRole       AccountUserRole `db:"owner_role" json:"owner_role"`
	OwnerCreatedAt  time.Time       `db:"owner_created_at" json:"owner_created_at"`
	SubjectID       uuid.UUID       `db:"subject_id" json:"subject_id"`
	SubjectName     string          `db:"subject_name" json:"subject_name"`
}

func (q *Queries) GetQuiz(ctx context.Context, quizID uuid.UUID) (GetQuizRow, error) {
	row := q.db.QueryRowContext(ctx, getQuiz, quizID)
	var i GetQuizRow
	err := row.Scan(
		&i.QuizID,
		&i.QuizTitle,
		&i.QuizSummary,
		&i.QuizTotalScore,
		&i.QuizDeadline,
		&i.QuizMaxAttempts,
		&i.QuizCreatedAt,
		&i.QuizQuestions,
		&i.OwnerID,
		&i.OwnerFirstName,
		&i.OwnerLastName,
		&i.OwnerRole,
		&i.OwnerCreatedAt,
		&i.SubjectID,
		&i.SubjectName,
	)
	return i, err
}

const getQuizItem = `-- name: GetQuizItem :many
SELECT 
	i.quiz_id AS quiz_id, 
	i.title AS quiz_title,
	i.summary AS quiz_summary,
	i.total_score::INT AS quiz_total_score,
	i.created_at AS quiz_created_at,
    i.deadline AS quiz_deadline,
    i.max_attempts::INT AS quiz_max_attempts,
	p.account_id AS owner_id,
	p.first_name AS owner_first_name,
	p.last_name AS owner_last_name,
	p.role AS owner_role,
	p.created_at AS owner_created_at,
	s.id AS subject_id,
	s.name AS subject_name
FROM quiz.info AS i
JOIN account.profile AS p
	ON p.account_id = i.owner_id
JOIN school.subject AS s
	ON s.id = i.subject_id
`

type GetQuizItemRow struct {
	QuizID          uuid.UUID       `db:"quiz_id" json:"quiz_id"`
	QuizTitle       string          `db:"quiz_title" json:"quiz_title"`
	QuizSummary     string          `db:"quiz_summary" json:"quiz_summary"`
	QuizTotalScore  int32           `db:"quiz_total_score" json:"quiz_total_score"`
	QuizCreatedAt   time.Time       `db:"quiz_created_at" json:"quiz_created_at"`
	QuizDeadline    sql.NullTime    `db:"quiz_deadline" json:"quiz_deadline"`
	QuizMaxAttempts int32           `db:"quiz_max_attempts" json:"quiz_max_attempts"`
	OwnerID         uuid.UUID       `db:"owner_id" json:"owner_id"`
	OwnerFirstName  string          `db:"owner_first_name" json:"owner_first_name"`
	OwnerLastName   string          `db:"owner_last_name" json:"owner_last_name"`
	OwnerRole       AccountUserRole `db:"owner_role" json:"owner_role"`
	OwnerCreatedAt  time.Time       `db:"owner_created_at" json:"owner_created_at"`
	SubjectID       uuid.UUID       `db:"subject_id" json:"subject_id"`
	SubjectName     string          `db:"subject_name" json:"subject_name"`
}

func (q *Queries) GetQuizItem(ctx context.Context) ([]GetQuizItemRow, error) {
	rows, err := q.db.QueryContext(ctx, getQuizItem)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetQuizItemRow
	for rows.Next() {
		var i GetQuizItemRow
		if err := rows.Scan(
			&i.QuizID,
			&i.QuizTitle,
			&i.QuizSummary,
			&i.QuizTotalScore,
			&i.QuizCreatedAt,
			&i.QuizDeadline,
			&i.QuizMaxAttempts,
			&i.OwnerID,
			&i.OwnerFirstName,
			&i.OwnerLastName,
			&i.OwnerRole,
			&i.OwnerCreatedAt,
			&i.SubjectID,
			&i.SubjectName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertAccountCredential = `-- name: InsertAccountCredential :exec

INSERT INTO account.credential (
    account_id,
    email,
    pwd_hash
)
VALUES (
    $1,
    $2,
    $3
)
`

type InsertAccountCredentialParams struct {
	AccountID uuid.UUID `db:"account_id" json:"account_id"`
	Email     string    `db:"email" json:"email"`
	PwdHash   string    `db:"pwd_hash" json:"pwd_hash"`
}

// ========================================
// ACCOUNT SCHEMA
// ========================================
func (q *Queries) InsertAccountCredential(ctx context.Context, arg InsertAccountCredentialParams) error {
	_, err := q.db.ExecContext(ctx, insertAccountCredential, arg.AccountID, arg.Email, arg.PwdHash)
	return err
}

const insertAccountProfile = `-- name: InsertAccountProfile :exec
INSERT INTO account.profile (
    account_id,
    first_name,
    last_name,
    role,
    created_at
)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5
)
`

type InsertAccountProfileParams struct {
	AccountID uuid.UUID       `db:"account_id" json:"account_id"`
	FirstName string          `db:"first_name" json:"first_name"`
	LastName  string          `db:"last_name" json:"last_name"`
	Role      AccountUserRole `db:"role" json:"role"`
	CreatedAt time.Time       `db:"created_at" json:"created_at"`
}

func (q *Queries) InsertAccountProfile(ctx context.Context, arg InsertAccountProfileParams) error {
	_, err := q.db.ExecContext(ctx, insertAccountProfile,
		arg.AccountID,
		arg.FirstName,
		arg.LastName,
		arg.Role,
		arg.CreatedAt,
	)
	return err
}

const insertQuizAnswer = `-- name: InsertQuizAnswer :exec
INSERT INTO quiz.answer (
    id,
    attempt_id,
    question_id,
    details
)
VALUES (
    $1,
    $2,
    $3,
    $4
)
`

type InsertQuizAnswerParams struct {
	ID         uuid.UUID       `db:"id" json:"id"`
	AttemptID  uuid.UUID       `db:"attempt_id" json:"attempt_id"`
	QuestionID uuid.UUID       `db:"question_id" json:"question_id"`
	Details    json.RawMessage `db:"details" json:"details"`
}

func (q *Queries) InsertQuizAnswer(ctx context.Context, arg InsertQuizAnswerParams) error {
	_, err := q.db.ExecContext(ctx, insertQuizAnswer,
		arg.ID,
		arg.AttemptID,
		arg.QuestionID,
		arg.Details,
	)
	return err
}

const insertQuizAttempt = `-- name: InsertQuizAttempt :exec
INSERT INTO quiz.attempt (
    id,
    quiz_id,
    user_id,
    started_at
)
VALUES (
    $1,
    $2,
    $3,
    $4
)
`

type InsertQuizAttemptParams struct {
	ID        uuid.UUID `db:"id" json:"id"`
	QuizID    uuid.UUID `db:"quiz_id" json:"quiz_id"`
	UserID    uuid.UUID `db:"user_id" json:"user_id"`
	StartedAt time.Time `db:"started_at" json:"started_at"`
}

func (q *Queries) InsertQuizAttempt(ctx context.Context, arg InsertQuizAttemptParams) error {
	_, err := q.db.ExecContext(ctx, insertQuizAttempt,
		arg.ID,
		arg.QuizID,
		arg.UserID,
		arg.StartedAt,
	)
	return err
}

const insertQuizInfo = `-- name: InsertQuizInfo :exec

INSERT INTO quiz.info (
    quiz_id,
    title,
    summary,
    subject_id,
    owner_id,
    max_attempts,
    total_score,
    deadline,
    created_at
)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9
)
`

type InsertQuizInfoParams struct {
	QuizID      uuid.UUID    `db:"quiz_id" json:"quiz_id"`
	Title       string       `db:"title" json:"title"`
	Summary     string       `db:"summary" json:"summary"`
	SubjectID   uuid.UUID    `db:"subject_id" json:"subject_id"`
	OwnerID     uuid.UUID    `db:"owner_id" json:"owner_id"`
	MaxAttempts int32        `db:"max_attempts" json:"max_attempts"`
	TotalScore  int          `db:"total_score" json:"total_score"`
	Deadline    sql.NullTime `db:"deadline" json:"deadline"`
	CreatedAt   time.Time    `db:"created_at" json:"created_at"`
}

// ========================================
// QUIZ SCHEMA
// ========================================
func (q *Queries) InsertQuizInfo(ctx context.Context, arg InsertQuizInfoParams) error {
	_, err := q.db.ExecContext(ctx, insertQuizInfo,
		arg.QuizID,
		arg.Title,
		arg.Summary,
		arg.SubjectID,
		arg.OwnerID,
		arg.MaxAttempts,
		arg.TotalScore,
		arg.Deadline,
		arg.CreatedAt,
	)
	return err
}

const insertQuizQuestion = `-- name: InsertQuizQuestion :exec
INSERT INTO quiz.question (
    id,
    quiz_id,
    title,
    score,
    details
)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5
)
`

type InsertQuizQuestionParams struct {
	ID      uuid.UUID       `db:"id" json:"id"`
	QuizID  uuid.UUID       `db:"quiz_id" json:"quiz_id"`
	Title   string          `db:"title" json:"title"`
	Score   int             `db:"score" json:"score"`
	Details json.RawMessage `db:"details" json:"details"`
}

func (q *Queries) InsertQuizQuestion(ctx context.Context, arg InsertQuizQuestionParams) error {
	_, err := q.db.ExecContext(ctx, insertQuizQuestion,
		arg.ID,
		arg.QuizID,
		arg.Title,
		arg.Score,
		arg.Details,
	)
	return err
}

const insertSchoolGroup = `-- name: InsertSchoolGroup :exec
INSERT INTO school.group (
    id,
    name
)
VALUES (
    $1, 
    $2
)
`

type InsertSchoolGroupParams struct {
	ID   uuid.UUID `db:"id" json:"id"`
	Name string    `db:"name" json:"name"`
}

func (q *Queries) InsertSchoolGroup(ctx context.Context, arg InsertSchoolGroupParams) error {
	_, err := q.db.ExecContext(ctx, insertSchoolGroup, arg.ID, arg.Name)
	return err
}

const insertSchoolSubject = `-- name: InsertSchoolSubject :exec

INSERT INTO school.subject (
    id,
    name
)
VALUES (
    $1, 
    $2
)
`

type InsertSchoolSubjectParams struct {
	ID   uuid.UUID `db:"id" json:"id"`
	Name string    `db:"name" json:"name"`
}

// ========================================
// SCHOOL SCHEMA
// ========================================
func (q *Queries) InsertSchoolSubject(ctx context.Context, arg InsertSchoolSubjectParams) error {
	_, err := q.db.ExecContext(ctx, insertSchoolSubject, arg.ID, arg.Name)
	return err
}

const insertStudent = `-- name: InsertStudent :exec
INSERT INTO account.student (
    account_id,
    group_id
)
VALUES (
    $1,
    $2
)
`

type InsertStudentParams struct {
	AccountID uuid.UUID `db:"account_id" json:"account_id"`
	GroupID   uuid.UUID `db:"group_id" json:"group_id"`
}

func (q *Queries) InsertStudent(ctx context.Context, arg InsertStudentParams) error {
	_, err := q.db.ExecContext(ctx, insertStudent, arg.AccountID, arg.GroupID)
	return err
}

const insertTeacher = `-- name: InsertTeacher :exec
INSERT INTO account.teacher (
    account_id,
    group_id,
    subject_id
)
VALUES (
    $1,
    $2,
    $3
)
`

type InsertTeacherParams struct {
	AccountID uuid.UUID `db:"account_id" json:"account_id"`
	GroupID   uuid.UUID `db:"group_id" json:"group_id"`
	SubjectID uuid.UUID `db:"subject_id" json:"subject_id"`
}

func (q *Queries) InsertTeacher(ctx context.Context, arg InsertTeacherParams) error {
	_, err := q.db.ExecContext(ctx, insertTeacher, arg.AccountID, arg.GroupID, arg.SubjectID)
	return err
}

const updateQuizAnswer = `-- name: UpdateQuizAnswer :exec
UPDATE quiz.answer 
SET 
    details = $1,
    score = $2,
    is_correct = $3
WHERE id = $4
`

type UpdateQuizAnswerParams struct {
	Details   json.RawMessage `db:"details" json:"details"`
	Score     int             `db:"score" json:"score"`
	IsCorrect bool            `db:"is_correct" json:"is_correct"`
	ID        uuid.UUID       `db:"id" json:"id"`
}

func (q *Queries) UpdateQuizAnswer(ctx context.Context, arg UpdateQuizAnswerParams) error {
	_, err := q.db.ExecContext(ctx, updateQuizAnswer,
		arg.Details,
		arg.Score,
		arg.IsCorrect,
		arg.ID,
	)
	return err
}

const updateQuizAttempt = `-- name: UpdateQuizAttempt :exec
UPDATE quiz.attempt 
SET 
    score = $1,
    ended_at = $2
WHERE id = $3
`

type UpdateQuizAttemptParams struct {
	Score   int          `db:"score" json:"score"`
	EndedAt sql.NullTime `db:"ended_at" json:"ended_at"`
	ID      uuid.UUID    `db:"id" json:"id"`
}

func (q *Queries) UpdateQuizAttempt(ctx context.Context, arg UpdateQuizAttemptParams) error {
	_, err := q.db.ExecContext(ctx, updateQuizAttempt, arg.Score, arg.EndedAt, arg.ID)
	return err
}
