// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package sqlc

import (
	"context"
	"database/sql"
	"encoding/json"
	"time"

	"github.com/google/uuid"
	"github.com/lib/pq"
)

const getDetailedUsers = `-- name: GetDetailedUsers :many
SELECT 
	p.account_id, 
	p.first_name, 
	p.last_name, 
	p.role, 
	p.created_at,
	s.group_id AS s_group_id,
	array_remove(array_agg(t.group_id), NULL)::UUID[] AS t_group_ids,
	array_remove(array_agg(t.subject_id), NULL)::UUID[] AS t_subject_ids
FROM account.profile AS p
LEFT JOIN account.student AS s
	ON s.account_id = p.account_id
LEFT JOIN account.teacher AS t
	ON t.account_id = p.account_id
GROUP BY 
	p.account_id, 
	p.first_name,
	p.last_name,
	p.role,
	p.created_at,
	s.group_id
`

type GetDetailedUsersRow struct {
	AccountID   uuid.UUID
	FirstName   string
	LastName    string
	Role        AccountUserRole
	CreatedAt   time.Time
	SGroupID    uuid.NullUUID
	TGroupIds   []uuid.UUID
	TSubjectIds []uuid.UUID
}

func (q *Queries) GetDetailedUsers(ctx context.Context) ([]GetDetailedUsersRow, error) {
	rows, err := q.db.QueryContext(ctx, getDetailedUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetDetailedUsersRow
	for rows.Next() {
		var i GetDetailedUsersRow
		if err := rows.Scan(
			&i.AccountID,
			&i.FirstName,
			&i.LastName,
			&i.Role,
			&i.CreatedAt,
			&i.SGroupID,
			pq.Array(&i.TGroupIds),
			pq.Array(&i.TSubjectIds),
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDomainQuiz = `-- name: GetDomainQuiz :one
SELECT 
	i.quiz_id AS quiz_id,
	i.title AS quiz_title,
	i.summary AS quiz_summary,
	i.owner_id AS quiz_owner_id,
	i.subject_id AS quiz_subject_id,
	i.total_score::INT AS quiz_total_score,
	i.deadline AS quiz_deadline,
	i.max_attempts::INT AS quiz_max_attempts,
	i.created_at AS quiz_created_at,
	json_agg(q.*)::JSONB AS quiz_questions
FROM quiz.info AS i
JOIN quiz.question AS q
	ON q.quiz_id = i.quiz_id
WHERE i.quiz_id = $1
`

type GetDomainQuizRow struct {
	QuizID          uuid.UUID
	QuizTitle       string
	QuizSummary     string
	QuizOwnerID     uuid.UUID
	QuizSubjectID   uuid.UUID
	QuizTotalScore  int32
	QuizDeadline    sql.NullTime
	QuizMaxAttempts int32
	QuizCreatedAt   time.Time
	QuizQuestions   json.RawMessage
}

func (q *Queries) GetDomainQuiz(ctx context.Context, quizID uuid.UUID) (GetDomainQuizRow, error) {
	row := q.db.QueryRowContext(ctx, getDomainQuiz, quizID)
	var i GetDomainQuizRow
	err := row.Scan(
		&i.QuizID,
		&i.QuizTitle,
		&i.QuizSummary,
		&i.QuizOwnerID,
		&i.QuizSubjectID,
		&i.QuizTotalScore,
		&i.QuizDeadline,
		&i.QuizMaxAttempts,
		&i.QuizCreatedAt,
		&i.QuizQuestions,
	)
	return i, err
}

const getQuiz = `-- name: GetQuiz :one
SELECT 
	i.quiz_id AS quiz_id, 
	i.title AS quiz_title,
	i.summary AS quiz_summary,
	i.total_score::INT AS quiz_total_score,
	i.deadline AS quiz_deadline,
	i.max_attempts AS quiz_max_attempts,
	i.created_at AS quiz_created_at,
    json_agg(q.*)::JSONB AS quiz_questions,
	p.account_id AS owner_id,
	p.first_name AS owner_first_name,
	p.last_name AS owner_last_name,
	p.role AS owner_role,
	p.created_at AS owner_created_at,
	s.id AS subject_id,
	s.name AS subject_name
FROM quiz.info AS i
JOIN quiz.question AS q
    ON q.quiz_id = i.quiz_id
JOIN account.profile AS p 
	ON p.account_id = i.owner_id
JOIN school.subject AS s
	ON s.id = i.subject_id
WHERE i.quiz_id = $1
GROUP BY
	i.quiz_id, 
	i.title,
	i.summary,
	i.total_score,
	i.deadline,
	i.max_attempts,
	i.created_at,
	p.account_id,
	p.first_name,
	p.last_name ,
	p.role,
	p.created_at,
	s.id,
	s.name
`

type GetQuizRow struct {
	QuizID          uuid.UUID
	QuizTitle       string
	QuizSummary     string
	QuizTotalScore  int32
	QuizDeadline    sql.NullTime
	QuizMaxAttempts int32
	QuizCreatedAt   time.Time
	QuizQuestions   json.RawMessage
	OwnerID         uuid.UUID
	OwnerFirstName  string
	OwnerLastName   string
	OwnerRole       AccountUserRole
	OwnerCreatedAt  time.Time
	SubjectID       uuid.UUID
	SubjectName     string
}

func (q *Queries) GetQuiz(ctx context.Context, quizID uuid.UUID) (GetQuizRow, error) {
	row := q.db.QueryRowContext(ctx, getQuiz, quizID)
	var i GetQuizRow
	err := row.Scan(
		&i.QuizID,
		&i.QuizTitle,
		&i.QuizSummary,
		&i.QuizTotalScore,
		&i.QuizDeadline,
		&i.QuizMaxAttempts,
		&i.QuizCreatedAt,
		&i.QuizQuestions,
		&i.OwnerID,
		&i.OwnerFirstName,
		&i.OwnerLastName,
		&i.OwnerRole,
		&i.OwnerCreatedAt,
		&i.SubjectID,
		&i.SubjectName,
	)
	return i, err
}

const getQuizItem = `-- name: GetQuizItem :many
SELECT 
	i.quiz_id AS quiz_id, 
	i.title AS quiz_title,
	i.summary AS quiz_summary,
	i.total_score::INT AS quiz_total_score,
	i.created_at AS quiz_created_at,
    i.deadline AS quiz_deadline,
    i.max_attempts::INT AS quiz_max_attempts,
	p.account_id AS owner_id,
	p.first_name AS owner_first_name,
	p.last_name AS owner_last_name,
	p.role AS owner_role,
	p.created_at AS owner_created_at,
	s.id AS subject_id,
	s.name AS subject_name
FROM quiz.info AS i
JOIN account.profile AS p
	ON p.account_id = i.owner_id
JOIN school.subject AS s
	ON s.id = i.subject_id
`

type GetQuizItemRow struct {
	QuizID          uuid.UUID
	QuizTitle       string
	QuizSummary     string
	QuizTotalScore  int32
	QuizCreatedAt   time.Time
	QuizDeadline    sql.NullTime
	QuizMaxAttempts int32
	OwnerID         uuid.UUID
	OwnerFirstName  string
	OwnerLastName   string
	OwnerRole       AccountUserRole
	OwnerCreatedAt  time.Time
	SubjectID       uuid.UUID
	SubjectName     string
}

func (q *Queries) GetQuizItem(ctx context.Context) ([]GetQuizItemRow, error) {
	rows, err := q.db.QueryContext(ctx, getQuizItem)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetQuizItemRow
	for rows.Next() {
		var i GetQuizItemRow
		if err := rows.Scan(
			&i.QuizID,
			&i.QuizTitle,
			&i.QuizSummary,
			&i.QuizTotalScore,
			&i.QuizCreatedAt,
			&i.QuizDeadline,
			&i.QuizMaxAttempts,
			&i.OwnerID,
			&i.OwnerFirstName,
			&i.OwnerLastName,
			&i.OwnerRole,
			&i.OwnerCreatedAt,
			&i.SubjectID,
			&i.SubjectName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertAccountCredential = `-- name: InsertAccountCredential :exec

INSERT INTO account.credential (
    account_id,
    email,
    pwd_hash
)
VALUES (
    $1,
    $2,
    $3
)
`

type InsertAccountCredentialParams struct {
	AccountID uuid.UUID
	Email     string
	PwdHash   string
}

// ========================================
// ACCOUNT SCHEMA
// ========================================
func (q *Queries) InsertAccountCredential(ctx context.Context, arg InsertAccountCredentialParams) error {
	_, err := q.db.ExecContext(ctx, insertAccountCredential, arg.AccountID, arg.Email, arg.PwdHash)
	return err
}

const insertAccountProfile = `-- name: InsertAccountProfile :exec
INSERT INTO account.profile (
    account_id,
    first_name,
    last_name,
    role,
    created_at
)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5
)
`

type InsertAccountProfileParams struct {
	AccountID uuid.UUID
	FirstName string
	LastName  string
	Role      AccountUserRole
	CreatedAt time.Time
}

func (q *Queries) InsertAccountProfile(ctx context.Context, arg InsertAccountProfileParams) error {
	_, err := q.db.ExecContext(ctx, insertAccountProfile,
		arg.AccountID,
		arg.FirstName,
		arg.LastName,
		arg.Role,
		arg.CreatedAt,
	)
	return err
}

const insertQuizAnswer = `-- name: InsertQuizAnswer :exec
INSERT INTO quiz.answer (
    id,
    attempt_id,
    question_id,
    score,
    is_correct
)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5
)
`

type InsertQuizAnswerParams struct {
	ID         uuid.UUID
	AttemptID  uuid.UUID
	QuestionID uuid.UUID
	Score      interface{}
	IsCorrect  bool
}

func (q *Queries) InsertQuizAnswer(ctx context.Context, arg InsertQuizAnswerParams) error {
	_, err := q.db.ExecContext(ctx, insertQuizAnswer,
		arg.ID,
		arg.AttemptID,
		arg.QuestionID,
		arg.Score,
		arg.IsCorrect,
	)
	return err
}

const insertQuizAttempt = `-- name: InsertQuizAttempt :exec
INSERT INTO quiz.attempt (
    id,
    quiz_id,
    user_id,
    content,
    score,
    started_at,
    ended_at
)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7
)
`

type InsertQuizAttemptParams struct {
	ID        uuid.UUID
	QuizID    uuid.UUID
	UserID    uuid.UUID
	Content   json.RawMessage
	Score     interface{}
	StartedAt time.Time
	EndedAt   sql.NullTime
}

func (q *Queries) InsertQuizAttempt(ctx context.Context, arg InsertQuizAttemptParams) error {
	_, err := q.db.ExecContext(ctx, insertQuizAttempt,
		arg.ID,
		arg.QuizID,
		arg.UserID,
		arg.Content,
		arg.Score,
		arg.StartedAt,
		arg.EndedAt,
	)
	return err
}

const insertQuizInfo = `-- name: InsertQuizInfo :exec

INSERT INTO quiz.info (
    quiz_id,
    title,
    summary,
    subject_id,
    owner_id,
    max_attempts,
    total_score,
    deadline,
    created_at
)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9
)
`

type InsertQuizInfoParams struct {
	QuizID      uuid.UUID
	Title       string
	Summary     string
	SubjectID   uuid.UUID
	OwnerID     uuid.UUID
	MaxAttempts int32
	TotalScore  interface{}
	Deadline    sql.NullTime
	CreatedAt   time.Time
}

// ========================================
// QUIZ SCHEMA
// ========================================
func (q *Queries) InsertQuizInfo(ctx context.Context, arg InsertQuizInfoParams) error {
	_, err := q.db.ExecContext(ctx, insertQuizInfo,
		arg.QuizID,
		arg.Title,
		arg.Summary,
		arg.SubjectID,
		arg.OwnerID,
		arg.MaxAttempts,
		arg.TotalScore,
		arg.Deadline,
		arg.CreatedAt,
	)
	return err
}

const insertQuizQuestion = `-- name: InsertQuizQuestion :exec
INSERT INTO quiz.question (
    id,
    quiz_id,
    variant,
    score,
    details
)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5
)
`

type InsertQuizQuestionParams struct {
	ID      uuid.UUID
	QuizID  uuid.UUID
	Variant QuizQuestionType
	Score   interface{}
	Details json.RawMessage
}

func (q *Queries) InsertQuizQuestion(ctx context.Context, arg InsertQuizQuestionParams) error {
	_, err := q.db.ExecContext(ctx, insertQuizQuestion,
		arg.ID,
		arg.QuizID,
		arg.Variant,
		arg.Score,
		arg.Details,
	)
	return err
}

const insertSchoolGroup = `-- name: InsertSchoolGroup :exec
INSERT INTO school.group (
    id,
    name
)
VALUES (
    $1, 
    $2
)
`

type InsertSchoolGroupParams struct {
	ID   uuid.UUID
	Name string
}

func (q *Queries) InsertSchoolGroup(ctx context.Context, arg InsertSchoolGroupParams) error {
	_, err := q.db.ExecContext(ctx, insertSchoolGroup, arg.ID, arg.Name)
	return err
}

const insertSchoolSubject = `-- name: InsertSchoolSubject :exec

INSERT INTO school.subject (
    id,
    name
)
VALUES (
    $1, 
    $2
)
`

type InsertSchoolSubjectParams struct {
	ID   uuid.UUID
	Name string
}

// ========================================
// SCHOOL SCHEMA
// ========================================
func (q *Queries) InsertSchoolSubject(ctx context.Context, arg InsertSchoolSubjectParams) error {
	_, err := q.db.ExecContext(ctx, insertSchoolSubject, arg.ID, arg.Name)
	return err
}

const insertStudent = `-- name: InsertStudent :exec
INSERT INTO account.student (
    account_id,
    group_id
)
VALUES (
    $1,
    $2
)
`

type InsertStudentParams struct {
	AccountID uuid.UUID
	GroupID   uuid.UUID
}

func (q *Queries) InsertStudent(ctx context.Context, arg InsertStudentParams) error {
	_, err := q.db.ExecContext(ctx, insertStudent, arg.AccountID, arg.GroupID)
	return err
}

const insertTeacher = `-- name: InsertTeacher :exec
INSERT INTO account.teacher (
    account_id,
    group_id,
    subject_id
)
VALUES (
    $1,
    $2,
    $3
)
`

type InsertTeacherParams struct {
	AccountID uuid.UUID
	GroupID   uuid.UUID
	SubjectID uuid.UUID
}

func (q *Queries) InsertTeacher(ctx context.Context, arg InsertTeacherParams) error {
	_, err := q.db.ExecContext(ctx, insertTeacher, arg.AccountID, arg.GroupID, arg.SubjectID)
	return err
}
