// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: quiz.sql

package sqlc

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
	"github.com/lib/pq"
)

const deleteQuizInfo = `-- name: DeleteQuizInfo :exec
DELETE FROM quiz.info
WHERE quiz_id = $1
`

func (q *Queries) DeleteQuizInfo(ctx context.Context, quizID uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteQuizInfo, quizID)
	return err
}

const finishAnswer = `-- name: FinishAnswer :exec
UPDATE quiz.answer
SET
    score = $1,
    is_correct = $2
WHERE id = $3
`

type FinishAnswerParams struct {
	Score     int       `db:"score" json:"score"`
	IsCorrect bool      `db:"is_correct" json:"is_correct"`
	ID        uuid.UUID `db:"id" json:"id"`
}

func (q *Queries) FinishAnswer(ctx context.Context, arg FinishAnswerParams) error {
	_, err := q.db.ExecContext(ctx, finishAnswer, arg.Score, arg.IsCorrect, arg.ID)
	return err
}

const finishAttempt = `-- name: FinishAttempt :exec
UPDATE quiz.attempt
SET 
    score = $1,
    ended_at = $2
WHERE id = $3
`

type FinishAttemptParams struct {
	Score   int          `db:"score" json:"score"`
	EndedAt sql.NullTime `db:"ended_at" json:"ended_at"`
	ID      uuid.UUID    `db:"id" json:"id"`
}

func (q *Queries) FinishAttempt(ctx context.Context, arg FinishAttemptParams) error {
	_, err := q.db.ExecContext(ctx, finishAttempt, arg.Score, arg.EndedAt, arg.ID)
	return err
}

const finishMultipleAnswer = `-- name: FinishMultipleAnswer :exec
UPDATE quiz.answer_multiple
SET
    selected_answer = $1
WHERE answer_id = $2
`

type FinishMultipleAnswerParams struct {
	SelectedAnswer []string  `db:"selected_answer" json:"selected_answer"`
	AnswerID       uuid.UUID `db:"answer_id" json:"answer_id"`
}

func (q *Queries) FinishMultipleAnswer(ctx context.Context, arg FinishMultipleAnswerParams) error {
	_, err := q.db.ExecContext(ctx, finishMultipleAnswer, pq.Array(arg.SelectedAnswer), arg.AnswerID)
	return err
}

const finishNumericAnswer = `-- name: FinishNumericAnswer :exec
UPDATE quiz.answer_numeric
SET
    selected_answer = $1
WHERE answer_id = $2
`

type FinishNumericAnswerParams struct {
	SelectedAnswer float64   `db:"selected_answer" json:"selected_answer"`
	AnswerID       uuid.UUID `db:"answer_id" json:"answer_id"`
}

func (q *Queries) FinishNumericAnswer(ctx context.Context, arg FinishNumericAnswerParams) error {
	_, err := q.db.ExecContext(ctx, finishNumericAnswer, arg.SelectedAnswer, arg.AnswerID)
	return err
}

const finishSingleAnswer = `-- name: FinishSingleAnswer :exec
UPDATE quiz.answer_single
SET
    selected_answer = $1
WHERE answer_id = $2
`

type FinishSingleAnswerParams struct {
	SelectedAnswer string    `db:"selected_answer" json:"selected_answer"`
	AnswerID       uuid.UUID `db:"answer_id" json:"answer_id"`
}

func (q *Queries) FinishSingleAnswer(ctx context.Context, arg FinishSingleAnswerParams) error {
	_, err := q.db.ExecContext(ctx, finishSingleAnswer, arg.SelectedAnswer, arg.AnswerID)
	return err
}

const insertQuizAnswer = `-- name: InsertQuizAnswer :exec
INSERT INTO quiz.answer (
    id,
    attempt_id,
    question_id
)
VALUES (
    $1,
    $2,
    $3
)
`

type InsertQuizAnswerParams struct {
	ID         uuid.UUID `db:"id" json:"id"`
	AttemptID  uuid.UUID `db:"attempt_id" json:"attempt_id"`
	QuestionID uuid.UUID `db:"question_id" json:"question_id"`
}

func (q *Queries) InsertQuizAnswer(ctx context.Context, arg InsertQuizAnswerParams) error {
	_, err := q.db.ExecContext(ctx, insertQuizAnswer, arg.ID, arg.AttemptID, arg.QuestionID)
	return err
}

const insertQuizAnswerMultiple = `-- name: InsertQuizAnswerMultiple :exec
INSERT INTO quiz.answer_multiple (
    answer_id,
    selected_answer
)
VALUES (
    $1,
    $2
)
`

type InsertQuizAnswerMultipleParams struct {
	AnswerID       uuid.UUID `db:"answer_id" json:"answer_id"`
	SelectedAnswer []string  `db:"selected_answer" json:"selected_answer"`
}

func (q *Queries) InsertQuizAnswerMultiple(ctx context.Context, arg InsertQuizAnswerMultipleParams) error {
	_, err := q.db.ExecContext(ctx, insertQuizAnswerMultiple, arg.AnswerID, pq.Array(arg.SelectedAnswer))
	return err
}

const insertQuizAnswerNumeric = `-- name: InsertQuizAnswerNumeric :exec
INSERT INTO quiz.answer_numeric (
    answer_id,
    selected_answer
)
VALUES (
    $1,
    $2
)
`

type InsertQuizAnswerNumericParams struct {
	AnswerID       uuid.UUID `db:"answer_id" json:"answer_id"`
	SelectedAnswer float64   `db:"selected_answer" json:"selected_answer"`
}

func (q *Queries) InsertQuizAnswerNumeric(ctx context.Context, arg InsertQuizAnswerNumericParams) error {
	_, err := q.db.ExecContext(ctx, insertQuizAnswerNumeric, arg.AnswerID, arg.SelectedAnswer)
	return err
}

const insertQuizAnswerSingle = `-- name: InsertQuizAnswerSingle :exec
INSERT INTO quiz.answer_single (
    answer_id,
    selected_answer
)
VALUES (
    $1,
    $2
)
`

type InsertQuizAnswerSingleParams struct {
	AnswerID       uuid.UUID `db:"answer_id" json:"answer_id"`
	SelectedAnswer string    `db:"selected_answer" json:"selected_answer"`
}

func (q *Queries) InsertQuizAnswerSingle(ctx context.Context, arg InsertQuizAnswerSingleParams) error {
	_, err := q.db.ExecContext(ctx, insertQuizAnswerSingle, arg.AnswerID, arg.SelectedAnswer)
	return err
}

const insertQuizAssigment = `-- name: InsertQuizAssigment :exec
INSERT INTO quiz.assignment(
    quiz_id,
    group_id
)
VALUES (
    $1,
    $2
)
`

type InsertQuizAssigmentParams struct {
	QuizID  uuid.UUID `db:"quiz_id" json:"quiz_id"`
	GroupID uuid.UUID `db:"group_id" json:"group_id"`
}

func (q *Queries) InsertQuizAssigment(ctx context.Context, arg InsertQuizAssigmentParams) error {
	_, err := q.db.ExecContext(ctx, insertQuizAssigment, arg.QuizID, arg.GroupID)
	return err
}

const insertQuizAttempt = `-- name: InsertQuizAttempt :exec
INSERT INTO quiz.attempt (
    id,
    quiz_id,
    user_id,
    started_at
)
VALUES (
    $1,
    $2,
    $3,
    $4
)
`

type InsertQuizAttemptParams struct {
	ID        uuid.UUID `db:"id" json:"id"`
	QuizID    uuid.UUID `db:"quiz_id" json:"quiz_id"`
	UserID    uuid.UUID `db:"user_id" json:"user_id"`
	StartedAt time.Time `db:"started_at" json:"started_at"`
}

func (q *Queries) InsertQuizAttempt(ctx context.Context, arg InsertQuizAttemptParams) error {
	_, err := q.db.ExecContext(ctx, insertQuizAttempt,
		arg.ID,
		arg.QuizID,
		arg.UserID,
		arg.StartedAt,
	)
	return err
}

const insertQuizInfo = `-- name: InsertQuizInfo :exec
INSERT INTO quiz.info (
    quiz_id,
    title,
    summary,
    subject_id,
    owner_id,
    max_attempts,
    total_score,
    deadline,
    created_at
)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9
)
`

type InsertQuizInfoParams struct {
	QuizID      uuid.UUID    `db:"quiz_id" json:"quiz_id"`
	Title       string       `db:"title" json:"title"`
	Summary     string       `db:"summary" json:"summary"`
	SubjectID   uuid.UUID    `db:"subject_id" json:"subject_id"`
	OwnerID     uuid.UUID    `db:"owner_id" json:"owner_id"`
	MaxAttempts int32        `db:"max_attempts" json:"max_attempts"`
	TotalScore  int          `db:"total_score" json:"total_score"`
	Deadline    sql.NullTime `db:"deadline" json:"deadline"`
	CreatedAt   time.Time    `db:"created_at" json:"created_at"`
}

func (q *Queries) InsertQuizInfo(ctx context.Context, arg InsertQuizInfoParams) error {
	_, err := q.db.ExecContext(ctx, insertQuizInfo,
		arg.QuizID,
		arg.Title,
		arg.Summary,
		arg.SubjectID,
		arg.OwnerID,
		arg.MaxAttempts,
		arg.TotalScore,
		arg.Deadline,
		arg.CreatedAt,
	)
	return err
}

const insertQuizQuestion = `-- name: InsertQuizQuestion :exec
INSERT INTO quiz.question (
    id,
    quiz_id,
    title,
    score,
    type
)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5
)
`

type InsertQuizQuestionParams struct {
	ID     uuid.UUID        `db:"id" json:"id"`
	QuizID uuid.UUID        `db:"quiz_id" json:"quiz_id"`
	Title  string           `db:"title" json:"title"`
	Score  int              `db:"score" json:"score"`
	Type   QuizQuestionType `db:"type" json:"type"`
}

func (q *Queries) InsertQuizQuestion(ctx context.Context, arg InsertQuizQuestionParams) error {
	_, err := q.db.ExecContext(ctx, insertQuizQuestion,
		arg.ID,
		arg.QuizID,
		arg.Title,
		arg.Score,
		arg.Type,
	)
	return err
}

const insertQuizQuestionMultiple = `-- name: InsertQuizQuestionMultiple :exec
INSERT INTO quiz.question_multiple (
    question_id,
    correct,
    options
)
VALUES (
    $1,
    $2,
    $3
)
`

type InsertQuizQuestionMultipleParams struct {
	QuestionID uuid.UUID `db:"question_id" json:"question_id"`
	Correct    []string  `db:"correct" json:"correct"`
	Options    []string  `db:"options" json:"options"`
}

func (q *Queries) InsertQuizQuestionMultiple(ctx context.Context, arg InsertQuizQuestionMultipleParams) error {
	_, err := q.db.ExecContext(ctx, insertQuizQuestionMultiple, arg.QuestionID, pq.Array(arg.Correct), pq.Array(arg.Options))
	return err
}

const insertQuizQuestionNumeric = `-- name: InsertQuizQuestionNumeric :exec
INSERT INTO quiz.question_numeric (
    question_id,
    correct
)
VALUES (
    $1,
    $2
)
`

type InsertQuizQuestionNumericParams struct {
	QuestionID uuid.UUID `db:"question_id" json:"question_id"`
	Correct    float64   `db:"correct" json:"correct"`
}

func (q *Queries) InsertQuizQuestionNumeric(ctx context.Context, arg InsertQuizQuestionNumericParams) error {
	_, err := q.db.ExecContext(ctx, insertQuizQuestionNumeric, arg.QuestionID, arg.Correct)
	return err
}

const insertQuizQuestionSingle = `-- name: InsertQuizQuestionSingle :exec
INSERT INTO quiz.question_single (
    question_id,
    correct,
    options
)
VALUES (
    $1,
    $2,
    $3
)
`

type InsertQuizQuestionSingleParams struct {
	QuestionID uuid.UUID `db:"question_id" json:"question_id"`
	Correct    string    `db:"correct" json:"correct"`
	Options    []string  `db:"options" json:"options"`
}

func (q *Queries) InsertQuizQuestionSingle(ctx context.Context, arg InsertQuizQuestionSingleParams) error {
	_, err := q.db.ExecContext(ctx, insertQuizQuestionSingle, arg.QuestionID, arg.Correct, pq.Array(arg.Options))
	return err
}
