// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: quiz.sql

package sqlc

import (
	"context"
	"database/sql"
	"encoding/json"
	"time"

	"github.com/google/uuid"
)

const deleteQuizInfo = `-- name: DeleteQuizInfo :exec
DELETE FROM quiz.info
WHERE quiz_id = $1
`

func (q *Queries) DeleteQuizInfo(ctx context.Context, quizID uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteQuizInfo, quizID)
	return err
}

const insertQuizAnswer = `-- name: InsertQuizAnswer :exec
INSERT INTO quiz.answer (
    id,
    attempt_id,
    question_id,
    details
)
VALUES (
    $1,
    $2,
    $3,
    $4
)
`

type InsertQuizAnswerParams struct {
	ID         uuid.UUID       `db:"id" json:"id"`
	AttemptID  uuid.UUID       `db:"attempt_id" json:"attempt_id"`
	QuestionID uuid.UUID       `db:"question_id" json:"question_id"`
	Details    json.RawMessage `db:"details" json:"details"`
}

func (q *Queries) InsertQuizAnswer(ctx context.Context, arg InsertQuizAnswerParams) error {
	_, err := q.db.ExecContext(ctx, insertQuizAnswer,
		arg.ID,
		arg.AttemptID,
		arg.QuestionID,
		arg.Details,
	)
	return err
}

const insertQuizAssigment = `-- name: InsertQuizAssigment :exec
INSERT INTO quiz.assignment(
    quiz_id,
    group_id
)
VALUES (
    $1,
    $2
)
`

type InsertQuizAssigmentParams struct {
	QuizID  uuid.UUID `db:"quiz_id" json:"quiz_id"`
	GroupID uuid.UUID `db:"group_id" json:"group_id"`
}

func (q *Queries) InsertQuizAssigment(ctx context.Context, arg InsertQuizAssigmentParams) error {
	_, err := q.db.ExecContext(ctx, insertQuizAssigment, arg.QuizID, arg.GroupID)
	return err
}

const insertQuizAttempt = `-- name: InsertQuizAttempt :exec
INSERT INTO quiz.attempt (
    id,
    quiz_id,
    user_id,
    started_at
)
VALUES (
    $1,
    $2,
    $3,
    $4
)
`

type InsertQuizAttemptParams struct {
	ID        uuid.UUID `db:"id" json:"id"`
	QuizID    uuid.UUID `db:"quiz_id" json:"quiz_id"`
	UserID    uuid.UUID `db:"user_id" json:"user_id"`
	StartedAt time.Time `db:"started_at" json:"started_at"`
}

func (q *Queries) InsertQuizAttempt(ctx context.Context, arg InsertQuizAttemptParams) error {
	_, err := q.db.ExecContext(ctx, insertQuizAttempt,
		arg.ID,
		arg.QuizID,
		arg.UserID,
		arg.StartedAt,
	)
	return err
}

const insertQuizInfo = `-- name: InsertQuizInfo :exec
INSERT INTO quiz.info (
    quiz_id,
    title,
    summary,
    subject_id,
    owner_id,
    max_attempts,
    total_score,
    deadline,
    created_at
)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9
)
`

type InsertQuizInfoParams struct {
	QuizID      uuid.UUID    `db:"quiz_id" json:"quiz_id"`
	Title       string       `db:"title" json:"title"`
	Summary     string       `db:"summary" json:"summary"`
	SubjectID   uuid.UUID    `db:"subject_id" json:"subject_id"`
	OwnerID     uuid.UUID    `db:"owner_id" json:"owner_id"`
	MaxAttempts int32        `db:"max_attempts" json:"max_attempts"`
	TotalScore  int          `db:"total_score" json:"total_score"`
	Deadline    sql.NullTime `db:"deadline" json:"deadline"`
	CreatedAt   time.Time    `db:"created_at" json:"created_at"`
}

func (q *Queries) InsertQuizInfo(ctx context.Context, arg InsertQuizInfoParams) error {
	_, err := q.db.ExecContext(ctx, insertQuizInfo,
		arg.QuizID,
		arg.Title,
		arg.Summary,
		arg.SubjectID,
		arg.OwnerID,
		arg.MaxAttempts,
		arg.TotalScore,
		arg.Deadline,
		arg.CreatedAt,
	)
	return err
}

const insertQuizQuestion = `-- name: InsertQuizQuestion :exec
INSERT INTO quiz.question (
    id,
    quiz_id,
    title,
    score,
    details
)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5
)
`

type InsertQuizQuestionParams struct {
	ID      uuid.UUID       `db:"id" json:"id"`
	QuizID  uuid.UUID       `db:"quiz_id" json:"quiz_id"`
	Title   string          `db:"title" json:"title"`
	Score   int             `db:"score" json:"score"`
	Details json.RawMessage `db:"details" json:"details"`
}

func (q *Queries) InsertQuizQuestion(ctx context.Context, arg InsertQuizQuestionParams) error {
	_, err := q.db.ExecContext(ctx, insertQuizQuestion,
		arg.ID,
		arg.QuizID,
		arg.Title,
		arg.Score,
		arg.Details,
	)
	return err
}

const updateQuizAnswer = `-- name: UpdateQuizAnswer :exec
UPDATE quiz.answer 
SET 
    details = $1,
    score = $2,
    is_correct = $3
WHERE id = $4
`

type UpdateQuizAnswerParams struct {
	Details   json.RawMessage `db:"details" json:"details"`
	Score     int             `db:"score" json:"score"`
	IsCorrect bool            `db:"is_correct" json:"is_correct"`
	ID        uuid.UUID       `db:"id" json:"id"`
}

func (q *Queries) UpdateQuizAnswer(ctx context.Context, arg UpdateQuizAnswerParams) error {
	_, err := q.db.ExecContext(ctx, updateQuizAnswer,
		arg.Details,
		arg.Score,
		arg.IsCorrect,
		arg.ID,
	)
	return err
}

const updateQuizAttempt = `-- name: UpdateQuizAttempt :exec
UPDATE quiz.attempt 
SET 
    score = $1,
    ended_at = $2
WHERE id = $3
`

type UpdateQuizAttemptParams struct {
	Score   int          `db:"score" json:"score"`
	EndedAt sql.NullTime `db:"ended_at" json:"ended_at"`
	ID      uuid.UUID    `db:"id" json:"id"`
}

func (q *Queries) UpdateQuizAttempt(ctx context.Context, arg UpdateQuizAttemptParams) error {
	_, err := q.db.ExecContext(ctx, updateQuizAttempt, arg.Score, arg.EndedAt, arg.ID)
	return err
}
