// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: school.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const insertSchoolGroup = `-- name: InsertSchoolGroup :exec
INSERT INTO school.group (
    id,
    name
)
VALUES (
    $1, 
    $2
)
`

type InsertSchoolGroupParams struct {
	ID   uuid.UUID `db:"id" json:"id"`
	Name string    `db:"name" json:"name"`
}

func (q *Queries) InsertSchoolGroup(ctx context.Context, arg InsertSchoolGroupParams) error {
	_, err := q.db.ExecContext(ctx, insertSchoolGroup, arg.ID, arg.Name)
	return err
}

const insertSchoolSubject = `-- name: InsertSchoolSubject :exec
INSERT INTO school.subject (
    id,
    name
)
VALUES (
    $1, 
    $2
)
`

type InsertSchoolSubjectParams struct {
	ID   uuid.UUID `db:"id" json:"id"`
	Name string    `db:"name" json:"name"`
}

func (q *Queries) InsertSchoolSubject(ctx context.Context, arg InsertSchoolSubjectParams) error {
	_, err := q.db.ExecContext(ctx, insertSchoolSubject, arg.ID, arg.Name)
	return err
}

const updateSchoolGroup = `-- name: UpdateSchoolGroup :exec
UPDATE school.group
SET 
    name = $1
WHERE id = $2
`

type UpdateSchoolGroupParams struct {
	Name string    `db:"name" json:"name"`
	ID   uuid.UUID `db:"id" json:"id"`
}

func (q *Queries) UpdateSchoolGroup(ctx context.Context, arg UpdateSchoolGroupParams) error {
	_, err := q.db.ExecContext(ctx, updateSchoolGroup, arg.Name, arg.ID)
	return err
}

const updateSchoolSubject = `-- name: UpdateSchoolSubject :exec
UPDATE school.subject
SET 
    name = $1
WHERE id = $2
`

type UpdateSchoolSubjectParams struct {
	Name string    `db:"name" json:"name"`
	ID   uuid.UUID `db:"id" json:"id"`
}

func (q *Queries) UpdateSchoolSubject(ctx context.Context, arg UpdateSchoolSubjectParams) error {
	_, err := q.db.ExecContext(ctx, updateSchoolSubject, arg.Name, arg.ID)
	return err
}
