// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: schoo.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const deleteSchoolGroup = `-- name: DeleteSchoolGroup :exec
DELETE FROM school.group
WHERE id = $1
`

func (q *Queries) DeleteSchoolGroup(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteSchoolGroup, id)
	return err
}

const deleteSchoolSubject = `-- name: DeleteSchoolSubject :exec
DELETE FROM school.subject
WHERE id = $1
`

func (q *Queries) DeleteSchoolSubject(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteSchoolSubject, id)
	return err
}
