common:
  logger:
    type: fake
    level: debug

usecase:
  user: real
  subject: stub
  quiz: stub
  group: stub
  answer: stub

service:
  generator: 
    auth: stub
    page: stub
  sender:
    mail: stub
  storage:
    type: stub
  validator:
    user: stub

transport:
  jwt: 
    parser: stub